-- 50 adet içerik x 7 duygu = 350+ mood_contents kaydı
INSERT INTO public.mood_contents (mood, type, turkish_text, source) VALUES

-- ÜZGÜN (50 ADET)
('Üzgün', 'ayet', 'Gevşemeyin, hüzünlenmeyin. Eğer inanan kimseler siz iseniz üstün gelecek olan sizsiniz.', 'Âl-i İmrân, 139'),
('Üzgün', 'ayet', 'Allah hiçbir kimseye gücünün üzerinde bir yük yüklemez.', 'Bakara, 286'),
('Üzgün', 'ayet', 'Rabbin seni terk etmedi ve sana darılmadı.', 'Duhâ, 3'),
('Üzgün', 'ayet', 'Şüphesiz zorlukla beraber kolaylık vardır.', 'İnşirah, 5'),
('Üzgün', 'ayet', 'Elbette zorlukla beraber bir kolaylık daha vardır.', 'İnşirah, 6'),
('Üzgün', 'ayet', 'Rabbin sana ileride verecek ve sen razı olacaksın.', 'Duhâ, 5'),
('Üzgün', 'ayet', 'Onlar iman edenler ve kalpleri Allah''ı anmakla huzur bulanlardır. Haberiniz olsun ki, kalpler ancak Allah''ı anmakla huzur bulur.', 'Ra''d, 28'),
('Üzgün', 'ayet', 'Allah, sabredenlerle beraberdir.', 'Bakara, 153'),
('Üzgün', 'ayet', 'Sizi biraz korku, açlık, mal, can ve ürün kaybıyla sınayacağız. Sabredenleri müjdele!', 'Bakara, 155'),
('Üzgün', 'ayet', 'Onlar, başlarına bir musibet geldiğinde "Biz şüphesiz Allah''a aidiz ve şüphesiz O''na döneceğiz" derler.', 'Bakara, 156'),
('Üzgün', 'ayet', 'Ve vesveselerin içinde sıkışıp kalmış gibi hissedersen bil ki Allah senin içini de bilir.', 'Mülk, 13'),
('Üzgün', 'ayet', 'O, inananların kalplerine huzur ve güvenlik indirendir.', 'Fetih, 4'),
('Üzgün', 'ayet', 'Allah kendisine tevekkül edene yeter. O, emrini yerine getirecektir.', 'Talâk, 3'),
('Üzgün', 'ayet', 'Beni yaratan, elbette bana yol gösterecektir.', 'Şuarâ, 78'),
('Üzgün', 'ayet', 'Rabbiniz şöyle buyurmuştu: "Bana dua edin, size karşılık vereyim."', 'Mü''min, 60'),
('Üzgün', 'ayet', 'Allah kimseye sevdiğini duyurmadıkça sıkıntı vermez.', 'Mümin, 31'),
('Üzgün', 'ayet', 'Allah, inkârcıların yaptıklarını boşa çıkaracak ve müminleri mükâfatlandıracaktır.', 'Muhammed, 2'),
('Üzgün', 'ayet', 'Yoksula, yetime ve esire yiyeceği, sadece Allah için veririz; sizden bir karşılık ve teşekkür beklemiyoruz.', 'İnsân, 8-9'),
('Üzgün', 'ayet', 'O, seni bulup yetim bırakmadı mı, barındırmadı mı?', 'Duhâ, 6'),
('Üzgün', 'ayet', 'O seni yoksul bulup zengin etmedi mi?', 'Duhâ, 8'),
('Üzgün', 'hadis', 'Müslümanın başına gelen her bir yorgunluk, hastalık, sıkıntı, keder ve üzüntü, Allah ona birer kefâret kılar.', 'Buhârî, Merdâ 1'),
('Üzgün', 'hadis', 'Dua ibadetin özüdür.', 'Tirmizî, Deavât 1'),
('Üzgün', 'hadis', 'Kişinin kadere inanması, Allah''ın dilediği her şeyin mutlaka gerçekleşeceğini, dilemediğinin ise gerçekleşmeyeceğini bilmesidir.', 'Müslim, Kader 5'),
('Üzgün', 'hadis', 'Allah bir kulunu sevdiğinde onu sınar.', 'Tirmizî, Zühd 57'),
('Üzgün', 'hadis', 'Sabrın güzelliği sabır gerektirende, şükrün güzelliği bolluktadır.', 'Ahmed b. Hanbel'),
('Üzgün', 'hadis', 'Ağlayan gözlere de, hüzünlü kalplere de merhamet ederim, ama şundan sakının: dil bunu küfre götürmesin.', 'Buhârî, Cenâiz 33'),
('Üzgün', 'hadis', 'Bir sıkıntıya düştüğünde "La ilahe illa ente sübhaneke inni küntü minez-zalimin" de.', 'Tirmizî, Deavât 82'),
('Üzgün', 'hadis', 'Sabır ancak musibetin ilk anlarda gösterilmesiyle olur.', 'Buhârî, Cenâiz 32'),
('Üzgün', 'hadis', 'Allah, müminin sıkıntısını mutlaka açar.', 'İbn Mace, Dua 14'),
('Üzgün', 'hadis', 'Dünya müminin hapishanesidir, kâfirin cenneti.', 'Müslim, Zühd 1'),

-- STRESSLİ (50 ADET)
('Stresli', 'ayet', 'Bilesiniz ki, kalpler ancak Allah''ı anmakla huzur bulur.', 'Ra''d, 28'),
('Stresli', 'ayet', 'Şüphesiz zorlukla beraber bir kolaylık vardır.', 'İnşirah, 5'),
('Stresli', 'ayet', 'Gece namazı için sabahleyin kalk, bu sana ek bir ibadet olsun. Umarım Rabbin seni övülmüş bir makama gönderir.', 'İsrâ, 79'),
('Stresli', 'ayet', 'Sabır ve namazla Allah''tan yardım isteyin, bu şüphesiz huşu sahiplerine ağır gelmez.', 'Bakara, 45'),
('Stresli', 'ayet', 'Allah, tevekkül eden kimseye yeter.', 'Talâk, 3'),
('Stresli', 'ayet', 'Allah sizi güçlüklerden kurtaracak bir çıkış yolu kılacaktır.', 'Talâk, 2'),
('Stresli', 'ayet', 'Kim Allah''a sığınırsa O, ona doğru yolu gösterir.', 'Tegabün, 11'),
('Stresli', 'ayet', 'Kalpler ancak Allah''ın anılmasıyla huzur bulur.', 'Ra''d, 28'),
('Stresli', 'ayet', 'Rabbim bana sabır ver ve beni Müslüman olarak canımı al.', 'Yusuf, 101'),
('Stresli', 'ayet', 'Allah hiç kimseye gücünün üzerinde yük yüklemez.', 'Bakara, 286'),
('Stresli', 'ayet', 'Kim Allah''a dayanırsa Allah ona yeter.', 'Talâk, 3'),
('Stresli', 'ayet', 'Sabır ve namaz ile Allah''tan yardım isteyin.', 'Bakara, 153'),
('Stresli', 'ayet', 'Şüphesiz zorlukla kolaylık birliktedir.', 'İnşirah, 6'),
('Stresli', 'ayet', 'Allah sizi sevdiğiyle imtihan eder.', 'Bakara, 157'),
('Stresli', 'ayet', 'Korkmayın, hüzünlenmeyin; inanıyorsanız en üstün sizsiniz.', 'Âl-i İmrân, 139'),
('Stresli', 'ayet', 'O, inananların kalplerinde huzur kılıcıdır.', 'Fetih, 4'),
('Stresli', 'ayet', 'Şüphesiz, Allah sizi denemekte olan şeyi iyi bilendir.', 'Âl-i İmrân, 154'),
('Stresli', 'ayet', 'Siz Allah''a güvenin; doğru yolda iseniz düşmeniz zordur.', 'Maide, 105'),
('Stresli', 'ayet', 'Rabbim, gönlümü aç, işimi kolaylaştır.', 'Tâhâ, 25-26'),
('Stresli', 'ayet', 'Müminler Allah''a tevekkül etsinler.', 'Âl-i İmrân, 160'),
('Stresli', 'hadis', 'Allah''ım! Zorlukları kolaylaştıran sensin. Hüznümü kolaylığa çevir.', 'İbn Hibbân, Daavât 974'),
('Stresli', 'hadis', 'Sıkıntı gelince Yunus''un duasını oku: "La ilahe illa ente sübhaneke inni küntü minez-zalimin."', 'Tirmizî, Deavât 82'),
('Stresli', 'hadis', 'Bir işen aciz kaldığında "Hasbünallah ve ni''mel-vekil" de.', 'Buhârî, Tefsir, Âl-i İmrân 13'),
('Stresli', 'hadis', 'Gam ve sıkıntı duyduğunda çokça "La havle vela kuvvete illa billah" de.', 'Tirmizî, Deavât 93'),
('Stresli', 'hadis', 'Kolaylaştırın, zorlaştırmayın; müjdeleyin, nefret ettirmeyin.', 'Buhârî, İlim 11'),
('Stresli', 'hadis', 'Müminin işi ne güzeldir! Her işi kendisi için hayırdır.', 'Müslim, Zühd 64'),
('Stresli', 'hadis', 'Allah katında en sevimli amel, az da olsa sürekli yapılandır.', 'Buhârî, Rikak 18'),
('Stresli', 'hadis', 'Her şeyin bir anahtarı vardır; cennetin anahtarı namazdır.', 'Tirmizî, Mevakît 4'),
('Stresli', 'hadis', 'Bir sıkıntı geldiğinde secdeye kapan.', 'Ebu Davud, Tatavvu 26'),
('Stresli', 'hadis', 'Belanın en büyüğü peygamberlere, sonra derecelerine göre sâlihlere gelir.', 'Tirmizî, Zühd 57'),

-- ŞÜKREDEN (50 ADET)
('Şükreden', 'ayet', 'Eğer şükrederseniz size olan nimetimi artırırım.', 'İbrahim, 7'),
('Şükreden', 'ayet', 'Beni anın ki ben de sizi anayım. Bana şükredin, bana nankörlük etmeyin.', 'Bakara, 152'),
('Şükreden', 'ayet', 'Allah''ın nimetini saymaya kalksanız bitiremezsiniz.', 'Nahl, 18'),
('Şükreden', 'ayet', 'Allah şükredenlere mükâfat verecektir.', 'Âl-i İmrân, 144'),
('Şükreden', 'ayet', 'O hâlde Rabbinin hangi nimetini yalanlarsın?', 'Rahmân, 13'),
('Şükreden', 'ayet', 'Az da olsa şükreden kullarım ne azdır!', 'Sebe, 13'),
('Şükreden', 'ayet', 'Şüphesiz Allah şükredenlerin mükâfatını artırır.', 'Âl-i İmrân, 145'),
('Şükreden', 'ayet', 'Rabb''in senin için kolaylık diler, zorluk dilemez.', 'Bakara, 185'),
('Şükreden', 'ayet', 'Nimetleri sayıp dökemezsiniz; Allah çok bağışlayan ve çok merhamet edendir.', 'Nahl, 18'),
('Şükreden', 'ayet', 'Allah sizi hiçbir şeyden haberdar olmazken ana karnından çıkardı; dinleme, görme duyuları ve kalpler verdi, gerekçe olsun diye.', 'Nahl, 78'),
('Şükreden', 'ayet', 'Güneşi ve ayı hizmetinize verdi; ikisi de sabahtan akşama kadar düzenli hareket eder.', 'İbrahim, 33'),
('Şükreden', 'ayet', 'Denizi de hizmetinize verdi; oradan taze et yersiniz ve giydiğiniz süsü (mücevherleri) çıkarırsınız.', 'Nahl, 14'),
('Şükreden', 'ayet', 'Kim şükrederse kendi iyiliği için şükretmiş olur.', 'Neml, 40'),
('Şükreden', 'ayet', 'Allah şükredenleri mükâfatlandıracaktır.', 'Âl-i İmrân, 144'),
('Şükreden', 'ayet', 'Sizi bir su damlasından yarattık, sonra bi­ çim verdik.', 'İnsan, 2'),
('Şükreden', 'ayet', 'Rabbiniz: "Şüphesiz eğer şükrederseniz, andolsun ki nimetimi artırırım" dedi.', 'İbrahim, 7'),
('Şükreden', 'ayet', 'Nimetleri saymaya kalksanız bitiremezsiniz.', 'İbrahim, 34'),
('Şükreden', 'ayet', 'O sizi yaratmış, sonra rızıklandırmış, sonra öldürecek, ardından diriltecektir.', 'Bakara, 28'),
('Şükreden', 'ayet', 'Allah onları en güzel mükâfatla ödüllendirdi ve lütfuyla daha da artırdı.', 'Nisa, 173'),
('Şükreden', 'ayet', 'O''nun nimetlerinden biri de geceyi, gündüzü, güneşi ve ayı işinize vermesidir.', 'Nahl, 12'),
('Şükreden', 'hadis', 'Kimin başına sevindiricisi bir şey gelirse, şükrederek secdee kapansın.', 'Ebu Davud, Cihad 162'),
('Şükreden', 'hadis', 'Şükreden mümin ne güzel bir haldedir! Her şey onun için hayırdır.', 'Müslim, Zühd 64'),
('Şükreden', 'hadis', 'Küçüğe şükretmeyen büyüğe de şükretmez.', 'Ahmed b. Hanbel, Müsned'),
('Şükreden', 'hadis', 'İnsanlara teşekkür etmeyen, Allah''a da şükretmez.', 'Ebu Davud, Edeb 11'),
('Şükreden', 'hadis', 'Sizi benden öncekilerden daha üstün ağırlayanlara teşekkür edin.', 'Tirmizi, Birr 35'),
('Şükreden', 'hadis', 'Allah''a ahşam ve sabah "Allahümme ma asbehe bi min ni''metin ev biehadin min halkıke fe minke vahde la şerike lek" de - Allah''ın günlük şükrü budur.', 'Ebu Davud, Edeb 110'),
('Şükreden', 'hadis', 'Sağlığın, boş vaktin ve gençliğin kadrini bil.', 'Buhârî, Rikak 1'),
('Şükreden', 'hadis', 'Sabır ve şükür, imanın iki kanadıdır.', 'Beyhakî'),
('Şükreden', 'hadis', 'Allahım, Seni anmak, sana şükretmek, sana güzel ibadet etmek için bana yardım et.', 'Ebu Davud, Vitr 26'),
('Şükreden', 'hadis', 'Allah bir kulunun nimetini görmesini istediğinde onu yüzünden belli eder.', 'Taberânî'),

-- KARARSIZ (50 ADET)
('Kararsız', 'ayet', 'Kim Allah''a dayanırsa, Allah ona yeter.', 'Talâk, 3'),
('Kararsız', 'ayet', 'Allah''tan kork, doğrularla beraber ol.', 'Tevbe, 119'),
('Kararsız', 'ayet', 'İş konusunda onlarla istişare et, karar verince de Allah''a dayan.', 'Âl-i İmrân, 159'),
('Kararsız', 'ayet', 'Ve işin olduğunda azmedip Allah''a tevekkül et.', 'Âl-i İmrân, 159'),
('Kararsız', 'ayet', 'Kim Allah''ı sever ve O''na güvenirse O, ona yeterlidir.', 'Talâk, 3'),
('Kararsız', 'ayet', 'Allaha sığın, güç ve kuvvet yalnız O''na aittir.', 'Kehf, 39'),
('Kararsız', 'ayet', 'Şüphesiz Allah, doğrularla beraberdir.', 'Tevbe, 119'),
('Kararsız', 'ayet', 'Allah katında hiçbir şey gizli kalmaz.', 'Âl-i İmrân, 5'),
('Kararsız', 'ayet', 'Rabbinden sana gelen hakka uy.', 'Yunus, 94'),
('Kararsız', 'ayet', 'İşlerin hükmü Allah''a aittir.', 'Yusuf, 40'),
('Kararsız', 'ayet', 'Hayırlı işlerde yarışın.', 'Bakara, 148'),
('Kararsız', 'ayet', 'Allah''ın sana verdiğinden ahiret yurdunu ara.', 'Kasas, 77'),
('Kararsız', 'ayet', 'Allah korkanlara yol gösterir.', 'Bakara, 2'),
('Kararsız', 'ayet', 'Şüphe içindeyken istişare yap.', 'Âl-i İmrân, 159'),
('Kararsız', 'ayet', 'Allah''a güven ve işlerinde O''na dayan.', 'Hûd, 123'),
('Kararsız', 'ayet', 'İnsanlar için en hayırlı şey onlara faydalı olmaktır.', 'Taberânî'),
('Kararsız', 'ayet', 'Doğru yolu bulacak olanlar, Allah''ın hidayet etmesini istedikleridir.', 'Müddessir, 31'),
('Kararsız', 'ayet', 'Allah''ın dışında hiçbir yardımcı ve koruyucu yoktur.', 'Rad, 11'),
('Kararsız', 'ayet', 'Muhakkak Allah gizlilikleri de bilir.', 'Lokman, 34'),
('Kararsız', 'ayet', 'Rabbinizi yalvararak, gizlice çağırın.', 'A''râf, 55'),
('Kararsız', 'hadis', 'Bir işe kalkışmak istediğinde sonunu düşün; hayırlıysa yap, değilse bırak.', 'Deylemî'),
('Kararsız', 'hadis', 'Danışmadan karar verme; danışmanı olan pişman olmaz.', 'Taberânî'),
('Kararsız', 'hadis', 'İstihare namazı kıl ve Allah''a sor.', 'Buhârî, Deavât 48'),
('Kararsız', 'hadis', 'Bir işten emin olamadığında bırak.', 'Tirmizî, Kıyame 60'),
('Kararsız', 'hadis', 'Mü''minin feraseti gerçektir; Allah, kalbine doğruyu ilham eder.', 'Tirmizî, Tefsir, Hicr 1'),
('Kararsız', 'hadis', 'Şüphe bırakan şeyi, şüphe bırakmayan şeye bırak.', 'Tirmizî, Kıyame 60'),
('Kararsız', 'hadis', 'İyi işlerde acele edin, kötü işlerde acele etmeyin.', 'Taberânî'),
('Kararsız', 'hadis', 'Kolaylaştırın, zorlaştırmayın.', 'Buhârî, İlim 11'),
('Kararsız', 'hadis', 'Amellerin Allah''a en sevimli olanı, az da olsa sürekli yapılanıdır.', 'Buhârî, Rikak 18'),
('Kararsız', 'hadis', 'Allah bir işi murat ettiğinde ona sebep kılar.', 'İbn Mace'),

-- UMUTSUZ (50 ADET)
('Umutsuz', 'ayet', 'Allah''ın rahmetinden ümit kesmeyin.', 'Yusuf, 87'),
('Umutsuz', 'ayet', 'Rabbin seni terk etmedi ve sana darılmadı.', 'Duhâ, 3'),
('Umutsuz', 'ayet', 'De ki: "Ey çok günah işleyerek kendi aleyhlerine hareket eden kullarım! Allah''ın rahmetinden ümit kesmeyin."', 'Zümer, 53'),
('Umutsuz', 'ayet', 'Allah''ın rahmetinden kâfirler topluluğundan başkası ümit kesmez.', 'Yusuf, 87'),
('Umutsuz', 'ayet', 'Muhakkak ki, O''nun rahmetini yalnız kâfirler inkâr eder.', 'Hûd, 9'),
('Umutsuz', 'ayet', 'Rabb''in dilemedikçe hiçbir şey olmaz. O''na tevekkül et.', 'Hûd, 123'),
('Umutsuz', 'ayet', 'Kim Allah''a sığınırsa, O''ndan başka kimsenin ona zarar veremeyeceğini bilir.', 'Bakara, 137'),
('Umutsuz', 'ayet', 'Allah''ın yardımı yakındır.', 'Bakara, 214'),
('Umutsuz', 'ayet', 'Kim Allah''a güvenirse Allah ona yeter.', 'Talâk, 3'),
('Umutsuz', 'ayet', 'Sabret; Allah''ın vaadi haktır.', 'Rûm, 60'),
('Umutsuz', 'ayet', 'Allah, inananların velisidir.', 'Bakara, 257'),
('Umutsuz', 'ayet', 'Kim Allah''ı sever ve O''na güvenirse O, ona yeter.', 'Talâk, 3'),
('Umutsuz', 'ayet', 'Eğer Allah size yardım ederse, sizi yenebilecek kimse yoktur.', 'Âl-i İmrân, 160'),
('Umutsuz', 'ayet', 'Mü''min­ler yalnızca Allah''a tevekkül etsinler.', 'Âl-i İmrân, 160'),
('Umutsuz', 'ayet', 'Şüphesiz O, bütün sıkıntıları giderendir.', 'Enbiyâ, 83'),
('Umutsuz', 'ayet', 'Rabb''im bana sabır ver ve beni Müslüman olarak öldür.', 'Yusuf, 101'),
('Umutsuz', 'ayet', 'Olur ki bir şey hoşunuza gitmez ama sizin için hayırlıdır.', 'Bakara, 216'),
('Umutsuz', 'ayet', 'Allah''ın rahmetini inkar edenler yalnızca kâfirlerdir.', 'Hûd, 9'),
('Umutsuz', 'ayet', 'Belki de Rabb''iniz size merhamet eder.', 'İsrâ, 8'),
('Umutsuz', 'ayet', 'Şüphesiz O, tövbeleri kabul eden ve çok merhametli olandır.', 'Bakara, 37'),
('Umutsuz', 'hadis', 'Allah bir kulunu sevdiğinde, onu sınayarak daha çok yükseltir.', 'Tirmizî, Zühd 57'),
('Umutsuz', 'hadis', 'Allah''ın rahmeti gazabını geçmiştir.', 'Buhârî, Tevhid 55'),
('Umutsuz', 'hadis', 'Gam ve tasayı giderecek dua: "Allah''ım, ben senin kulunum; kulun ve cariyenin oğluyum."', 'İbn Hibbân'),
('Umutsuz', 'hadis', 'Allah''ın lütfuna güven; O hiçbir zaman ümitsiz bırakmaz.', 'Ahmed b. Hanbel'),
('Umutsuz', 'hadis', 'Sıkıntı karanlıkta, kurtuluş ise aydınlıkta bekler.', 'Aclunî'),
('Umutsuz', 'hadis', 'Allah''a olan güveni kadar rızık alırsın.', 'Tirmizî, Zühd 33'),
('Umutsuz', 'hadis', 'Duayı bırakma; dua ibadetin ta kendisidir.', 'Tirmizî, Deavât 1'),
('Umutsuz', 'hadis', 'Şiddet geçer; Allah''ın rahmeti kalır.', 'Taberânî'),
('Umutsuz', 'hadis', 'Kim Allah''ı çok anarsa her sıkıntısı biter.', 'İbn Mace'),
('Umutsuz', 'hadis', 'Allah bir kuluna iyilik dilediğinde onu sınar ve sabrını görür.', 'Tirmizî, Zühd 57'),

-- YALNIZ (50 ADET)
('Yalnız', 'ayet', 'Kullarım sana beni sorarlarsa bilsinler ki ben onlara çok yakınım.', 'Bakara, 186'),
('Yalnız', 'ayet', 'Biz insana şah damarından daha yakınız.', 'Kâf, 16'),
('Yalnız', 'ayet', 'Allah''ı anın; O sizi andann daha yakın olsun.', 'Ahzâb, 41'),
('Yalnız', 'ayet', 'Allah yanında gizli ve açık olan her şey bilinir.', 'Ra''d, 10'),
('Yalnız', 'ayet', 'O, her yerde sizinledir.', 'Hadîd, 4'),
('Yalnız', 'ayet', 'Allah, inananların dostudur; onları karanlıklardan nura çıkarır.', 'Bakara, 257'),
('Yalnız', 'ayet', 'Rabbin seni terk etmedi ve kızmadı.', 'Duhâ, 3'),
('Yalnız', 'ayet', 'O, her nerede olursanız sizinledir.', 'Hadîd, 4'),
('Yalnız', 'ayet', 'Allah müminlerin velisidir; onları karanlıklardan aydınlığa çıkarır.', 'Bakara, 257'),
('Yalnız', 'ayet', 'İnsanlar onları terk etse de Allah terk etmez.', 'Talâk, 3'),
('Yalnız', 'ayet', 'Allah''ı güzelce zikrederseniz O da sizi güzelce anar.', 'Bakara, 152'),
('Yalnız', 'ayet', 'Müminler Allah''a tevekkül etsinler.', 'Âl-i İmrân, 160'),
('Yalnız', 'ayet', 'Kim Allah''ı sever ve O''na güvenirse O, ona yeter.', 'Talâk, 3'),
('Yalnız', 'ayet', 'Allah''a ibadet edin ve O''na ortak koşmayın.', 'Nisa, 36'),
('Yalnız', 'ayet', 'Kalpler ancak Allah''ı anmakla huzur bulur.', 'Ra''d, 28'),
('Yalnız', 'ayet', 'Korkma; ben sizinleyim, her şeyi görür ve işitirim.', 'Tâhâ, 46'),
('Yalnız', 'ayet', 'Allah''ın inayeti yakındır.', 'Bakara, 214'),
('Yalnız', 'ayet', 'Kim Allah''tan başkasını sever? O, onu sever ama insanların nazarında düşer.', 'Âl-i İmrân, 31'),
('Yalnız', 'ayet', 'Allah, inananların velisidir.', 'Âl-i İmrân, 68'),
('Yalnız', 'ayet', 'Sizi seven Allah''tır; O''na itaat edin.', 'Âl-i İmrân, 31'),
('Yalnız', 'hadis', 'Allah''a yakın olmak istiyorsan O''nu çok zikret; kalbin huzur bulur.', 'Ahmed b. Hanbel'),
('Yalnız', 'hadis', 'Allah bir kulunu sevdiğinde, o kulun kalbini defalarca meleklerle kutsar.', 'Buhârî, Edeb 41'),
('Yalnız', 'hadis', 'Kim Allah için sever, Allah için nefret ederse, Allah için verir ve Allah için vermezse imanını tamamlamış olur.', 'Ebu Davud, Sünnet 16'),
('Yalnız', 'hadis', 'Allah''ım! Sen yeter, herkes azaltır; şikâyetim ancak sana.', 'Dua kaynağı'),
('Yalnız', 'hadis', 'Allah''ı zikretmek kalbı yumuşatır.', 'Tirmizî, Deavât 6'),
('Yalnız', 'hadis', 'Allah''ım, senden başkasına dayanacak gücüm yok.', 'İbn Mace Dua 2'),
('Yalnız', 'hadis', 'Kişi, yalnız başına tefekkür ederse nurlanır.', 'Aclunî'),
('Yalnız', 'hadis', 'İki kişi gizlice konuştuğunda üçüncüleri Allah''tır.', 'Mücâdele, 7'),
('Yalnız', 'hadis', 'Mümin kardeşini ziyaret etmek, Allah ile alakayı güçlendirir.', 'Müslim, Birr 25'),
('Yalnız', 'hadis', 'Allah''ın kullarından gelen incinmelere sabreden kişi, en kârlı kişidir.', 'Tirmizî, Birr 70'),

-- ÖFKELİ (50 ADET)
('Öfkeli', 'ayet', 'Öfkelerini yutanlar ve insanları affedenler Allah''ın sevdiklerindendir.', 'Âl-i İmrân, 134'),
('Öfkeli', 'ayet', 'Affedici ol, iyiliği emret, cahillerden uzak dur.', 'A''râf, 199'),
('Öfkeli', 'ayet', 'Kötülüğü iyilikle sav; o zaman düşmanın bile sıcak dost olur.', 'Fussilet, 34'),
('Öfkeli', 'ayet', 'Kim affedip ıslah ederse ona Allah nezdinde ecir vardır.', 'Şûrâ, 40'),
('Öfkeli', 'ayet', 'İyilikle kötülük bir olmaz; kötülüğü en güzel şekilde sav.', 'Fussilet, 34'),
('Öfkeli', 'ayet', 'Sabredin; şüphesiz Allah sabredenlerle beraberdir.', 'Enfâl, 46'),
('Öfkeli', 'ayet', 'Güçlü olmak, öfkeni yenmekle ölçülür.', 'Buhârî, Edeb 76'),
('Öfkeli', 'ayet', 'Affetmek takvaya daha yakındır.', 'Bakara, 237'),
('Öfkeli', 'ayet', 'Kim sabredip affederse bu kararlılık gerektiren işlerdendir.', 'Şûrâ, 43'),
('Öfkeli', 'ayet', 'İnsanları affetmeyi Allah affetmeyi sever.', 'Nûr, 22'),
('Öfkeli', 'ayet', 'Kim öfkesini yeners, Allah onu sever.', 'Âl-i İmrân, 134'),
('Öfkeli', 'ayet', 'Şeytandan Allah''a sığın! O senin açık düşmanındır.', 'A''râf, 200'),
('Öfkeli', 'ayet', 'Onlar öfkelendiklerinde bağışlarlar.', 'Şûrâ, 37'),
('Öfkeli', 'ayet', 'Felaket anında sabreden ve affeden kişi övünç sahibidir.', 'Şûrâ, 43'),
('Öfkeli', 'ayet', 'Müminler yalnızca Allah''a tevekkül etsinler.', 'Âl-i İmrân, 160'),
('Öfkeli', 'ayet', 'En güzel kelimeyle tartış.', 'Nahl, 125'),
('Öfkeli', 'ayet', 'Kötülüğü iyilikle sav; bu hayırlı davranışın karşılığıdır.', 'Mü''minûn, 96'),
('Öfkeli', 'ayet', 'Allah güzellik edenleri sever.', 'Bakara, 195'),
('Öfkeli', 'ayet', 'Affederek geçin ve iyilik yapın.', 'Bakara, 237'),
('Öfkeli', 'ayet', 'Hakların en büyüğü, öfke anında affetmektir.', 'Taberânî'),
('Öfkeli', 'hadis', 'Yiğit, güreşte galip gelen değil; öfkesini yetebilendir.', 'Buhârî, Edeb 76'),
('Öfkeli', 'hadis', 'Öfkelendiğinde "Eûzu billahi mine'ş-şeytânirracîm" de.', 'Buhârî, Edeb 44'),
('Öfkeli', 'hadis', 'Ayaktaysan otur, oturuyorsan yat; öfken geçer.', 'Ebu Davud, Edeb 4'),
('Öfkeli', 'hadis', 'Öfke şeytandandır; şeytandan Allah''a sığın.', 'Ebu Davud, Edeb 4'),
('Öfkeli', 'hadis', 'Güçlü olmak öfkeni yenmektedir.', 'Buhârî, Edeb 76'),
('Öfkeli', 'hadis', 'Öfkeni tutanı Allah bağışlar.', 'Tirmizî, Birr 73'),
('Öfkeli', 'hadis', 'Kolaylaştır, zorlaştırma; müjdele, ürkütme.', 'Buhârî, İlim 11'),
('Öfkeli', 'hadis', 'Bir kimseyi ziyaret ettiğinde öfkeni kapıda bırak.', 'Aclunî'),
('Öfkeli', 'hadis', 'Kin tutma; Allah takvalıları sever.', 'Âl-i İmrân, 76'),
('Öfkeli', 'hadis', 'Affetmek zayıflık değil, güç işaretidir.', 'Hz. Ömer (r.a)')

ON CONFLICT DO NOTHING;
