-- 100 Adet 'Bunu Biliyor Muydun?' (islamic_facts) Ä°Ã§eriÄŸi
INSERT INTO islamic_facts (fact_text, source) VALUES
('Kur''an-Ä± Kerim''de 114 sure bulunmaktadÄ±r ve bu surelerin en uzunu Bakara, en kÄ±sasÄ± Kevser Suresi''dir.', 'Genel Bilgi'),
('Peygamber Efendimiz (s.a.v) Medine''ye hicret ettikten sonra inÅŸa edilen ilk mescid Kuba Mescidi''dir.', 'Siyer'),
('Ä°slamiyetâ€™i kabul eden ilk sahabeler Hz. Hatice, Hz. Ali, Hz. Ebu Bekir ve Hz. Zeyd bin Harise''dir.', 'Ä°slam Tarihi'),
('Zemzem suyunun ismi, Hz. Hacer validemizin suya "dur dur" anlamÄ±na gelen "zem zem" demesinden gelmektedir.', 'TarihÃ§e'),
('Kur''an-Ä± Kerim''de ismi geÃ§en tek kadÄ±n Hz. Meryem''dir.', 'Kur''an-Ä± Kerim'),
('Peygamberimiz (s.a.v) Veda HaccÄ±''nda irad ettiÄŸi Veda Hutbesi''ni yaklaÅŸÄ±k 100.000 sahabeye okumuÅŸtur.', 'Siyer'),
('EzanÄ± rÃ¼yasÄ±nda gÃ¶rerek Peygamberimize anlatan ve ilk defa okunmasÄ±na vesile olan sahabe Abdullah bin Zeyd''dir.', 'Hadis'),
('Ä°slam aleminde ilk kÃ¼tÃ¼phane Emevi halifesi Halid bin Yezid tarafÄ±ndan Åam''da kurulmuÅŸtur.', 'Ä°slam Tarihi'),
('Kur''an-Ä± Kerim''de "Ahmed" ismiyle mÃ¼jdelenen peygamber, Hz. Muhammed (s.a.v)''dir (Saff Suresi 6. Ayet).', 'Kur''an-Ä± Kerim'),
('BeÅŸ vakit namaz, MiraÃ§ gecesinde farz kÄ±lÄ±nmÄ±ÅŸtÄ±r.', 'Siyer'),
('Mekke''nin Fethi, Hicret''in 8. yÄ±lÄ±nda (Miladi 630) Ramazan ayÄ±nda gerÃ§ekleÅŸmiÅŸtir.', 'Ä°slam Tarihi'),
('Uhud SavaÅŸÄ±''nda Peygamberimizin (s.a.v) amcasÄ± Hz. Hamza ÅŸehit edilmiÅŸ ve "Åehitlerin Efendisi" unvanÄ±nÄ± almÄ±ÅŸtÄ±r.', 'Siyer'),
('Kur''an-Ä± Kerim toplam 30 cÃ¼z, 604 sayfa ve 6236 (yaygÄ±n kabule gÃ¶re) ayetten oluÅŸur.', 'Genel Bilgi'),
('Kur''an''Ä±n kalbi olarak nitelendirilen sure Yasin Suresi''dir.', 'Hadis'),
('Cennetin 8, Cehennemin ise 7 kapÄ±sÄ± olduÄŸu Kuran ve Hadislerde bildirilmektedir.', 'Akaid'),
('Peygamber Efendimiz (s.a.v) hayatÄ± boyunca sadece bir kez hacca gitmiÅŸtir (Veda HaccÄ±).', 'Siyer'),
('Ä°slam fÄ±khÄ±nda dÃ¶rt bÃ¼yÃ¼k hak mezhep vardÄ±r: Hanefi, Åafii, Maliki, Hanbeli.', 'FÄ±kÄ±h'),
('Peygamber Efendimizin (s.a.v) sÃ¼t annesi Halime validemizdir.', 'Siyer'),
('Kadir Gecesi, Kuran''da "bin aydan daha hayÄ±rlÄ±" olarak nitelendirilen gecedir.', 'Kadir Suresi'),
('Bedir SavaÅŸÄ±, MÃ¼slÃ¼manlarÄ±n mÃ¼ÅŸriklere karÅŸÄ± kazandÄ±ÄŸÄ± ilk bÃ¼yÃ¼k ve en Ã¶nemli savaÅŸtÄ±r.', 'Ä°slam Tarihi'),
('DÃ¼nyanÄ±n en eski Ã¼niversitelerinden biri olan Karaviyyin Ãœniversitesi, 859 yÄ±lÄ±nda Fas''ta FatÄ±ma el-FÄ±hri tarafÄ±ndan kurulmuÅŸtur.', 'Ä°slam Tarihi'),
('Ä°lk Ä°slam donanmasÄ±, Hz. Osman dÃ¶neminde Åam Valisi Muaviye tarafÄ±ndan kurulmuÅŸ ve KÄ±brÄ±s fethedilmiÅŸtir.', 'Ä°slam Tarihi'),
('Ayetel KÃ¼rsi, Kur''an-Ä± Kerim''deki en yÃ¼ce ayet olarak kabul edilir ve Bakara Suresi''nin 255. ayetidir.', 'Hadis'),
('Ä°slam tarihinin ilk kadÄ±n ÅŸehidi Hz. SÃ¼meyye''dir.', 'Ä°slam Tarihi'),
('Suffe ehli (Ashab-Ä± Suffa), Mescid-i Nebevi''de eÄŸitim gÃ¶ren ve bekar olan sahabelere verilen isimdir.', 'Ä°slam EÄŸitim Tarihi'),
('MÃ¼slÃ¼manlarÄ±n ilk kÄ±blesi KudÃ¼s''te bulunan Mescid-i Aksa''dÄ±r.', 'Kur''an-Ä± Kerim'),
('Kur''an-Ä± Kerim''in kitap haline getirilmesi (Mushaf) Hz. Ebu Bekir dÃ¶neminde, Ã§oÄŸaltÄ±lmasÄ± ise Hz. Osman dÃ¶neminde yapÄ±lmÄ±ÅŸtÄ±r.', 'Ä°slam Tarihi'),
('Peygamberimiz (s.a.v) dÃ¶neminde yapÄ±lan ilk nÃ¼fus sayÄ±mÄ± Hicretin 1. yÄ±lÄ±nda Medine''de yapÄ±lmÄ±ÅŸ, 1500 MÃ¼slÃ¼man tespit edilmiÅŸtir.', 'Ä°slam Tarihi'),
('Ebu Hureyre (r.a), hadis rivayetinde en Ã§ok hadis nakleden (5374 hadis) sahabedir.', 'Hadis UsulÃ¼'),
('Mekke''den Medine''ye hicret ederken Peygamber Efendimize sÄ±ÄŸÄ±nakta (Sevr MaÄŸarasÄ±) arkadaÅŸlÄ±k eden sahabe Hz. Ebu Bekir''dir.', 'Siyer'),
('KÄ±yamet gÃ¼nÃ¼nde amellerin tartÄ±lacaÄŸÄ± mizan terazisinin haber verildiÄŸi Enbiya Suresi 47. ayettir.', 'Akaid'),
('Ä°slam tasavvufunun bÃ¼yÃ¼k temsilcilerinden Mevlana Celaleddin Rumi, Mesnevi adlÄ± eserini FarsÃ§a yazmÄ±ÅŸtÄ±r.', 'Edebiyat / Tasavvuf'),
('Ay takviminin (Hicri takvim) baÅŸlangÄ±cÄ± Hz. Ã–mer devrinde, Hicret olayÄ± (Miladi 622) esas alÄ±narak kabul edilmiÅŸtir.', 'Ä°slam Tarihi'),
('EndÃ¼lÃ¼s Emevi Devleti sayesinde Ä°slam medeniyeti Avrupa''ya TaÅŸÄ±nmÄ±ÅŸ (Ä°spanya), bilim ve felsefede RÃ¶nesans''Ä± etkilemiÅŸtir.', 'Ä°slam Tarihi'),
('Peygamber Efendimizin doÄŸduÄŸu yÄ±la (Miladi 571) Kabe''yi yÄ±kmaya gelen Ebrehe ordusu yÃ¼zÃ¼nden "Fil YÄ±lÄ±" denmiÅŸtir.', 'Siyer'),
('Kur''an''da adÄ± geÃ§en meleklerden Mikail (a.s), doÄŸa olaylarÄ± ve rÄ±zÄ±klarÄ±n daÄŸÄ±tÄ±mÄ±ndan sorumludur.', 'Akaid / Melekler'),
('MÃ¼ezzinlerin atasÄ± sayÄ±lan Hz. Bilal-i HabeÅŸi, Kabe''nin Ã¼zerinde ilk ezanÄ± okuyan kiÅŸidir.', 'Ä°slam Tarihi'),
('Peygamber Efendimizin vefat ettiÄŸi ve kabrinin bulunduÄŸu yere "Ravza-i Mutahhara" (Tertemiz BahÃ§e) denir.', 'Siyer'),
('Sadaka-i FÄ±tÄ±r (Fitre), Ramazan ayÄ±nÄ±n sonuna yetiÅŸen ve temel ihtiyaÃ§larÄ±ndan fazla mala sahip olan MÃ¼slÃ¼manlara vaciptir.', 'FÄ±kÄ±h'),
('Cuma namazÄ±nÄ±n farziyeti Hicret sÄ±rasÄ±nda Kuba''dan Medine''ye geÃ§erken Ranuna Vadisi''nde inen ayetle baÅŸlamÄ±ÅŸtÄ±r.', 'Siyer / FÄ±kÄ±h'),
('Peygamberimizin (s.a.v) peygamberliÄŸini ilk tasdik eden erkek HÄ±ristiyan alimi Varaka bin Nevfel''dir.', 'Siyer'),
('Ä°slamiyet Ã¶ncesi Mekke dÃ¶nemindeki cehalet, putperestlik ve zulÃ¼m devrine "Cahiliye DÃ¶nemi" denir.', 'Tarih'),
('Mescid-i Haram''daki Hacer-Ã¼l Esved (Siyah TaÅŸ), cennetten indiÄŸine inanÄ±lan kutsal bir taÅŸtÄ±r.', 'Dini Ä°nanÄ±ÅŸ'),
('TeyemmÃ¼m, suyun bulunmadÄ±ÄŸÄ± veya kullanÄ±lamadÄ±ÄŸÄ± durumlarda temiz toprakla yapÄ±lan abdest tÃ¼rÃ¼dÃ¼r.', 'FÄ±kÄ±h'),
('Namazda okunmasÄ± farz olan sure Fatiha Suresi''dir. â€œFatihasÄ±z namaz olmazâ€ hadisi mevcuttur.', 'Hadis / FÄ±kÄ±h'),
('Safa ve Merve tepeleri arasÄ±nda gidip gelerek yapÄ±lan ibadete "Sa''y" denir. Hz. Hacer''in su arayÄ±ÅŸÄ±nÄ± temsil eder.', 'Hac / Umre'),
('Hudeybiye AntlaÅŸmasÄ± (Hicri 6. yÄ±l), MÃ¼slÃ¼manlar ile Mekkeli MÃ¼ÅŸrikler arasÄ±ndaki ilk barÄ±ÅŸ antlaÅŸmasÄ±dÄ±r.', 'Siyer'),
('Hz. YÃ»suf''un (a.s) hikayesi Kuran-Ä± Kerim''de "Ahsen-Ã¼l Kasas" (KÄ±ssalarÄ±n En GÃ¼zeli) olarak nitelendirilir.', 'Yusuf Suresi'),
('Abdestin farzÄ± Kuran-Ä± Kerim''e gÃ¶re dÃ¶rttÃ¼r: YÃ¼zÃ¼ yÄ±kamak, kollarÄ±nÄ± yÄ±kamak, baÅŸÄ± meshetmek ve ayaklarÄ± yÄ±kamak.', 'Maide Suresi 6. Ayet'),
('Ä°lk OsmanlÄ± Halifesi Yavuz Sultan Selim''dir. MÄ±sÄ±r Seferi ile halifelik OsmanlÄ±''ya geÃ§miÅŸtir.', 'OsmanlÄ± Tarihi'),
('Peygamber Efendimiz "Ben, gÃ¼zel ahlakÄ± tamamlamak Ã¼zere gÃ¶nderildim" buyurmuÅŸtur.', 'Hadis-i Åerif'),
('Cennetle mÃ¼jdelenen 10 sahabeye "AÅŸere-i MÃ¼beÅŸÅŸere" denmektedir.', 'Ä°slam Tarihi'),
('Hz. Ã–mer dÃ¶neminde fethedilen KudÃ¼s, Selahaddin Eyyubi tarafÄ±ndan 1187''de HaÃ§lÄ±lardan geri alÄ±nmÄ±ÅŸtÄ±r.', 'Ä°slam Tarihi'),
('Dinimizde faiz (Riba), haksÄ±z kazanÃ§ ve sÃ¶mÃ¼rÃ¼ aracÄ± olduÄŸu iÃ§in Kuran ayetleriyle kesin olarak haram kÄ±lÄ±nmÄ±ÅŸtÄ±r.', 'FÄ±kÄ±h / Ekonomi'),
('Ensar, Mekke''den Medine''ye hicret eden MÃ¼slÃ¼manlara kucak aÃ§an ve yardÄ±m eden Medineli MÃ¼slÃ¼manlara denir.', 'Terimler'),
('Muhacir, dinleri uÄŸruna Mekke''den Medine''ye (veya HabeÅŸistan''a) gÃ¶Ã§ etmek zorunda kalan sahabelere denir.', 'Terimler'),
('Ä°stiÅŸare, Kuran-Ä± Kerim''de Ã¶vÃ¼len ve bir iÅŸe karar vermeden Ã¶nce ehil kiÅŸilere danÄ±ÅŸmak anlamÄ±na gelen sÃ¼nnettir.', 'Åura Suresi'),
('Hz. Davud''a (a.s) Zebur, Hz. Musa''ya (a.s) Tevrat, Hz. Ä°sa''ya (a.s) Ä°ncil, Hz. Muhammed''e (s.a.v) Kuran verilmiÅŸtir.', 'Akaid'),
('Kaza namazÄ±, vaktinde kÄ±lÄ±nmayan farz namazlarÄ±n daha sonra kÄ±lÄ±nmasÄ±na verilen isimdir.', 'FÄ±kÄ±h'),
('Peygamberimiz dÃ¶neminde inÅŸa edilen 3 kutsal mescid vardÄ±r: Mescid-i Haram (Mekke), Mescid-i Nebevi (Medine), Mescid-i Aksa (KudÃ¼s).', 'Genel Bilgi'),
('Ramazan ayÄ±nda oruÃ§lu iken unutarak yemek veya iÃ§mek orucu bozmaz.', 'FÄ±kÄ±h'),
('Nisab miktarÄ±, zekÃ¢t vermekle yÃ¼kÃ¼mlÃ¼ olmak iÃ§in dinin belirlediÄŸi asgari zenginlik Ã¶lÃ§Ã¼sÃ¼dÃ¼r.', 'FÄ±kÄ±h'),
('Peygamber Efendimiz (s.a.v) doÄŸmadan Ã¶nce babasÄ± Abdullah''Ä±, altÄ± yaÅŸÄ±ndayken de annesi Amine''yi kaybetmiÅŸtir.', 'Siyer'),
('Eshab-Ä± Kehf (Yedi Uyurlar) isimli genÃ§ler, Kuran-Ä± Kerim''in Kehf suresinde anlatÄ±lÄ±r. YÃ¼zlerce yÄ±l maÄŸarada uyumuÅŸlardÄ±r.', 'Kur''an-Ä± Kerim'),
('Karz-Ä± Hasen, hiÃ§bir maddi Ã§Ä±kar (faiz) beklemeden Allah rÄ±zasÄ± iÃ§in verilen gÃ¼zel borÃ§tur.', 'Kavramlar'),
('Ä°slamiyetâ€™e inanan ve MÃ¼slÃ¼man olan ilk TÃ¼rk devleti Ä°dil BulgarlarÄ± (Ä°til Bulgar HanlÄ±ÄŸÄ±) olarak tarihi kaynaklarda geÃ§er.', 'TÃ¼rk-Ä°slam Tarihi'),
('DivanÃ¼ LÃ»gatiâ€™t-TÃ¼rk, KaÅŸgarlÄ± Mahmud tarafÄ±ndan yazÄ±lan, Ä°slam dÃ¼nyasÄ±nda ilk kapsamlÄ± TÃ¼rk dili sÃ¶zlÃ¼ÄŸÃ¼dÃ¼r.', 'Edebiyat / Tarih'),
('Hutbe, Cuma ve bayram namazlarÄ±nda imamÄ±n minbere Ã§Ä±karak cemaate hitap edip nasihat vermesidir.', 'Dini Ä°badetler'),
('Mizah (ÅŸaka) yaparken yalan sÃ¶ylememek ve kimseyi kÄ±rÄ±cÄ±, alaycÄ± konuÅŸmamak SÃ¼nnettir.', 'Ahlak'),
('DÃ¼nya tarihinde hastane konseptinin temelleri Ä°slam medeniyetindeki BÃ®mÃ¢ristan veya DÃ¢rÃ¼ÅŸÅŸifÃ¢ denilen kurumlara dayanÄ±r.', 'Ä°slam Medeniyeti'),
('GusÃ¼l abdestinin farzÄ± Ã¼Ã§tÃ¼r: AÄŸza su verip Ã§alkalamak, buruna su Ã§ekmek, bÃ¼tÃ¼n vÃ¼cudu kuru yer kalmayacak ÅŸekilde yÄ±kamak.', 'FÄ±kÄ±h'),
('Sahabe, Peygamber Efendimizi imanlÄ± olarak gÃ¶rÃ¼p, sohbetinde bulunan ve MÃ¼slÃ¼man olarak vefat eden kiÅŸilere denir.', 'Terimler'),
('TÃ¢biÃ®n, Sahabeleri gÃ¶rÃ¼p, onlardan eÄŸitim alan ve MÃ¼slÃ¼man olarak vefat eden nesle verilen isimdir.', 'Terimler'),
('Hz. Ali (r.a), hem Peygamberimizin amcasÄ± Ebu Talipâ€™in oÄŸlu, hem evlatlÄ±ÄŸÄ±, hem de kÄ±zÄ± Hz. FatÄ±maâ€™nÄ±n eÅŸidir.', 'Ä°slam Tarihi'),
('Nebi, kendisine yeni bir kitap indirilmeyen, kendinden Ã¶nceki resulÃ¼n ÅŸeriatÄ±nÄ± devam ettiren peygamber demektir.', 'Akaid'),
('Resul, kendisine Allah tarafÄ±ndan yeni bir kitap ve yeni bir ÅŸeriat gÃ¶nderilen peygamberlere denir.', 'Akaid'),
('Vahiy meleÄŸi Cebrail (a.s), Kuran boyunca Ruh, Ruh-Ã¼l KudÃ¼s ve Ruhuâ€™l-Emin unvanlarÄ±yla da anÄ±lÄ±r.', 'Melekler'),
('Amel defteri, insanlarÄ±n dÃ¼nya hayatÄ±nda yaptÄ±klarÄ± iyi ve kÃ¶tÃ¼ her iÅŸin (amellerin) Kiraman Katibin melekleri tarafÄ±ndan yazÄ±ldÄ±ÄŸÄ± kayÄ±tlarÄ± temsil eder.', 'Akaid'),
('DÃ¶rt BÃ¼yÃ¼k Halife sÄ±rasÄ±yla Hz. Ebu Bekir, Hz. Ã–mer, Hz. Osman ve Hz. Ali''dir (HulefÃ¢-i RÃ¢ÅŸidÃ®n).', 'Ä°slam Tarihi'),
('Ä°lk halifeler dÃ¶nemi, halifelerin istiÅŸare (seÃ§im/onay) ile baÅŸa gelmeleri sebebiyle Ä°slam Cumhuriyeti dÃ¶nemi olarak da anÄ±lÄ±r.', 'Tarih'),
('Hz. Osman amansÄ±z ÅŸehadeti sÄ±rasÄ±nda Kur''an-Ä± Kerim (Mushaf) okumaktaydÄ± ve kanÄ± Kuran sayfalarÄ±na damlamÄ±ÅŸtÄ±r.', 'Ä°slam Tarihi'),
('Mihrab, camilerde kÄ±ble yÃ¶nÃ¼nde bulunan ve imamÄ±n namaz kÄ±ldÄ±rÄ±rken durduÄŸu, genellikle kubbeli veya oyuk bÃ¶lÃ¼mdÃ¼r.', 'Mimari'),
('Minber, camilerde Cuma ve Bayram hutbelerinin okunduÄŸu, genellikle merdivenli, yÃ¼ksek yapÄ±dÄ±r.', 'Mimari'),
('KÃ¼rsÃ¼, camilerde din bilginlerinin (vaizlerin) cemaate hitap ettiÄŸi (vaaz verdiÄŸi), yerden biraz yÃ¼ksekÃ§e oturma yeridir.', 'Mimari'),
('Åam''daki Emevi Camii, minare mimarisinin ilk ve en erken devasa Ã¶rneÄŸi olarak bilinir.', 'Mimari'),
('NamazÄ±n iÃ§indeki farzlar (ÅŸartlar) altÄ±dÄ±r: Ä°ftitah tekbiri, KÄ±yam (ayakta durma), KÄ±raat (Kur''an okuma), RÃ¼kÃ», Secde, Ka''de-i AhÃ®re (Son oturuÅŸ).', 'FÄ±kÄ±h'),
('NamazÄ±n dÄ±ÅŸÄ±ndaki farzlarÄ± (hazÄ±rlÄ±k) altÄ±dÄ±r: Hadesten taharet (abdest/gusÃ¼l), Necasetten taharet (elbise/mekan temizliÄŸi), Setr-i avret (Ã¶rtÃ¼nme), Ä°stikbal-i kÄ±ble, Vakit, Niyet.', 'FÄ±kÄ±h'),
('Hz. Musa''nÄ±n (a.s), Firavun''un zulmÃ¼nden kurtulmak iÃ§in asasÄ±yla KÄ±zÄ±ldeniz''i ikiye ayÄ±rmasÄ± bir mucizedir.', 'KÄ±ssalar'),
('Mimar Sinan, Åehzade Camii''ni "Ã§Ä±raklÄ±k", SÃ¼leymaniye''yi "kalfalÄ±k", Selimiye''yi ise "ustalÄ±k" eseri olarak nitelendirmiÅŸtir.', 'Tarih'),
('Tasavvuf, Ä°slam dininin ahlaki ve kalbi arÄ±nmasÄ±nÄ± ele alan, kiÅŸiyi Allah rÄ±zasÄ±na ulaÅŸtÄ±rmayÄ± hedefleyen batÄ±ni (iÃ§sel) bir ilimdir.', 'Tasavvuf'),
('VakÄ±f kÃ¼ltÃ¼rÃ¼, Ä°slam medeniyetinde o kadar geliÅŸmiÅŸtir ki gÃ¶Ã§men kuÅŸlarÄ±n tedavisi (Gurabahane-i Laklakan) iÃ§in bile vakÄ±flar kurulmuÅŸtur.', 'Medeniyet'),
('Yunus Emre, 13. ve 14. yÃ¼zyÄ±llarda yaÅŸamÄ±ÅŸ, ÅŸiirleriyle Anadolu''da TÃ¼rk-Ä°slam tasavvufunun en bÃ¼yÃ¼k temsilcisi olmuÅŸtur.', 'Tasavvuf EdebiyatÄ±'),
('Taif YolculuÄŸu, Mekkelilerin baskÄ±sÄ± artÄ±nca Peygamberimizin himaye bulmak iÃ§in Taif''e gitmesi ancak orada taÅŸlanarak geri dÃ¶nmesidir.', 'Siyer'),
('Mirac, Peygamber Efendimizin Mescid-i Haram''dan Mescid-i Aksa''ya, oradan da YÃ¼ce makamlara (SidretÃ¼''l-MÃ¼nteha) yÃ¼kseliÅŸi mucizesidir.', 'Siyer'),
('Muvatta, Ä°mam Malik tarafÄ±ndan derlenen, Ä°slam dÃ¼nyasÄ±nÄ±n bilinen en eski ve gÃ¼venilir hadis/fÄ±kÄ±h kitabÄ±dÄ±r.', 'Hadis'),
('KÃ¼tÃ¼b-i Sitte, SÃ¼nni Ä°slam dÃ¼nyasÄ±nda en Ã§ok gÃ¼venilen altÄ± sahih hadis kitabÄ±na verilen isimdir (Buhari, MÃ¼slim, Ebu Davud, Tirmizi, Nesai, Ä°bn Mace).', 'Hadis'),
('Allah''Ä±n varlÄ±k, birlik ve eÅŸsizliÄŸini kÄ±sa ve en Ã¶z ÅŸekilde anlatan Kuran suresi Ä°hlas Suresidir.', 'Kuran-Ä± Kerim'),
('ZekÃ¢t kelime olarak arÄ±nma, temizlenme ve Ã§oÄŸalma/bereketlenme anlamlarÄ±na gelir.', 'FÄ±kÄ±h'),
('Mescid-i DÄ±rar, mÃ¼nafÄ±klar tarafÄ±ndan Ä°slam toplumunu bÃ¶lmek iÃ§in yapÄ±lmÄ±ÅŸ ve Tevbe Suresi 107. ayet uyarÄ±nca Peygamberimiz tarafÄ±ndan yÄ±ktÄ±rÄ±lmÄ±ÅŸtÄ±r.', 'Siyer'),
('SÄ±la-i Rahim, akrabalarÄ± ziyaret etmek, gÃ¶zetmek ve yardÄ±mlaÅŸmak anlamÄ±na gelir ve dinimizde Ã¶mrÃ¼ bereketlendirdiÄŸine inanÄ±lÄ±r.', 'Ahlak');
-- 100 Adet 'TevekkÃ¼l Vakti' (tevekkul_vakti) Ä°Ã§eriÄŸi
INSERT INTO tevekkul_vakti (content_text, source) VALUES
('Allah bize yeter, O ne gÃ¼zel vekildir.', 'Ã‚l-i Ä°mrÃ¢n Suresi, 173'),
('Kim Allah''a tevekkÃ¼l ederse, O, ona yeter.', 'TalÃ¢k Suresi, 3'),
('HiÃ§bir dert sonsuz deÄŸildir, her gecenin bir sabahÄ± vardÄ±r; yeter ki umut edip dua kapÄ±sÄ±nÄ± Ã§almayÄ± bil.', 'Mevlana'),
('GevÅŸemeyin, hÃ¼zÃ¼nlenmeyin. EÄŸer (gerÃ§ekten) inanÄ±yorsanÄ±z, Ã¼stÃ¼n gelecek olan sizsiniz.', 'Ã‚l-i Ä°mran Suresi, 139'),
('De ki: "Allah''Ä±n bizim iÃ§in yazdÄ±ÄŸÄ±ndan baÅŸkasÄ± bize asla isabet etmez. O, bizim MevlÃ¢mÄ±zdÄ±r. MÃ¼minler yalnÄ±zca Allah''a tevekkÃ¼l etsinler."', 'Tevbe Suresi, 51'),
('Vermek istemeseydi, istemek vermezdi.', 'Necip FazÄ±l KÄ±sakÃ¼rek'),
('Kulun kalbi Rabbiyle huzur bulur; endiÅŸelerin en ilacÄ± O''na teslim olmaktÄ±r.', 'Ä°mam Åafii'),
('Dert etme, dua et.', 'Mevlana'),
('Sen Allah''a gÃ¼ven, hiÃ§ beklemediÄŸin anda Ã§iÃ§ek aÃ§ar umutlar.', 'Anonim'),
('Rabbinin seni terk etmediÄŸini ve sana darÄ±lmadÄ±ÄŸÄ±nÄ± unutma.', 'DuhÃ¢ Suresi, 3'),
('Her zorlukla beraber bir kolaylÄ±k vardÄ±r.', 'Ä°nÅŸirah Suresi, 5'),
('Allah gÃ¶ÄŸe yÃ¼kselmeyi deÄŸil, secdeye inmeyi Ã¶ÄŸretti bize.', 'Anonim'),
('EÄŸer Allah size yardÄ±m ederse, artÄ±k sizi yenilgiye uÄŸratacak kimse yoktur.', 'Ã‚l-i Ä°mrÃ¢n Suresi, 160'),
('Kader gayrete aÅŸÄ±ktÄ±r.', 'Yunus Emre'),
('SabÄ±r, aÄŸrÄ±larÄ± dindiren en gÃ¼zel acÄ± ilaÃ§tÄ±r.', 'Hz. Ali (r.a)'),
('DuasÄ± "HayÄ±rlÄ±sÄ±" olanÄ±n, sonu hep "Mutluluk" olur.', 'Anonim'),
('Kalpler ancak Allah''Ä± anmakla huzur bulur.', 'Ra''d Suresi, 28'),
('Nasibin olanÄ± kaybetmezsin, onu senden baÅŸkasÄ± da yiyemez. O halde bu telaÅŸ niye?', 'Hz. Mevlana'),
('Allah, sabredenleri sever.', 'Ã‚l-i Ä°mran Suresi, 146'),
('Bazen her ÅŸeyin bittiÄŸini sanÄ±rsÄ±n, oysa O (c.c) yeniden baÅŸlatÄ±r.', 'Anonim'),
('Ä°yi bir niyetle yola Ã§Ä±karsan, Rabbin sana kapÄ±larÄ±n en hayÄ±rlÄ±sÄ±nÄ± aÃ§ar.', 'Hz. Ã–mer (r.a)'),
('GerÃ§ek zenginlik; kalp zenginliÄŸidir.', 'Hadis-i Åerif'),
('Allah kuluna kÃ¢fi deÄŸil midir?', 'ZÃ¼mer Suresi, 36'),
('Kendi kendine yeten tek varlÄ±k O''dur; sen kul ol, gerisini O''na bÄ±rak.', 'Anonim'),
('UmmadÄ±ÄŸÄ±n bir kapÄ± aÃ§Ä±lÄ±r, sen o zaman Rabbinin kudretini izle.', 'Mevlana'),
('Muhakkak ki Allah, tevekkÃ¼l edenleri sever.', 'Ã‚l-i Ä°mrÃ¢n Suresi, 159'),
('En karanlÄ±k an, ÅŸafaÄŸÄ±n sÃ¶kmesine en yakÄ±n andÄ±r.', 'Anonim'),
('HÃ¼zÃ¼n ki en Ã§ok yakÄ±ÅŸandÄ±r bize. Belki de en Ã§ok anladÄ±ÄŸÄ±mÄ±zdÄ±r.', 'Hilmi Yavuz'),
('SabÄ±r, kurtuluÅŸun anahtarÄ±dÄ±r.', 'Hz. Ebubekir (r.a)'),
('Bir kapÄ± kapanÄ±rsa, Allah bin kapÄ± aÃ§ar.', 'Yunus Emre'),
('KaranlÄ±ÄŸa sÃ¶veceÄŸine bir mum yak; duaya dur, kalbini nurlandÄ±r.', 'Anonim'),
('Kendine gel, yepyeni bir gÃ¼n doÄŸuyor. DÃ¼n dÃ¼ndÃ¼, bugÃ¼nÃ¼ Allah iÃ§in yaÅŸa.', 'Hz. Mevlana'),
('O ne gÃ¼zel Mevla ve ne gÃ¼zel yardÄ±mcÄ±dÄ±r.', 'EnfÃ¢l Suresi, 40'),
('Beni yaratan elbet bana yol gÃ¶sterecektir.', 'ÅuarÃ¢ Suresi, 78'),
('Allah bir kapÄ±yÄ± kaparsa, bin kapÄ±yÄ± aÃ§ar. Sen kapÄ±da beklemeyi bil.', 'Anonim'),
('Her ÅŸeyin bir vakti vardÄ±r; vaktinden Ã¶nce Ã§iÃ§ek aÃ§maz.', 'Hz. Mevlana'),
('Kaderin ne getireceÄŸi bilinmez, ama tevekkÃ¼l eden bilir ki gelen Allah''tandÄ±r.', 'Anonim'),
('Ã–lÃ¼den diriyi, diriden Ã¶lÃ¼yÃ¼ Ã§Ä±karan O''dur. Her zorluÄŸun arkasÄ±ndan kolaylÄ±k gÃ¶nderen de O''dur.', 'RÃ»m Suresi, 19'),
('GÃ¶nlÃ¼n sÄ±kÄ±ldÄ±ÄŸÄ±nda semaya bak, oradan rahmet iner.', 'Hz. Ali (r.a)'),
('Allah''tan umut kesilmez.', 'AtasÃ¶zÃ¼'),
('Dua, inanan insana verilmiÅŸ en bÃ¼yÃ¼k silahtÄ±r.', 'Hadis-i Åerif'),
('Ben hÃ¼znÃ¼mÃ¼ ve kederimi ancak Allah''a ÅŸikayet ederim.', 'Yusuf Suresi, 86'),
('Senin iÃ§in yazÄ±lan senden baÅŸkasÄ±na gitmez.', 'Hadis-i Åerif'),
('Oluver (KÃ¼n) der, o da hemen oluverir (FeyekÃ»n).', 'YÃ¢sÃ®n Suresi, 82'),
('Teslimiyet, denizin Ã¼zerinde taÅŸÄ±nmak demektir.', 'Mevlana'),
('Hayra vesile olan, hayrÄ± yapan gibidir.', 'Hadis-i Åerif'),
('Nasip, ne gÃ¼zel bir kelimedir; ne eksiÄŸi vardÄ±r, ne fazlasÄ±.', 'Anonim'),
('HayÄ±rlÄ±sÄ± demekten daha gÃ¼zel bir dua yoktur.', 'Hz. Mevlana'),
('GÃ¶klerin ve yerin ordularÄ± Allah''Ä±ndÄ±r. O her ÅŸeyi bilir, hÃ¼kÃ¼m ve hikmet sahibidir.', 'Fetih Suresi, 4'),
('KuÅŸku duyma; O, her duayÄ± iÅŸitendir.', 'GÃ¢fir Suresi, 60'),
('Ä°nsanÄ± insana sadece dua en gÃ¼zel ÅŸekilde anlatÄ±r.', 'Anonim'),
('Niyetin halis ise, Allah sana en dikenli yolu bile gÃ¼l bahÃ§esi eyler.', 'Anonim'),
('ÅÃ¼phesiz Allah''Ä±n rahmeti iyilik edenlere Ã§ok yakÄ±ndÄ±r.', 'A''rÃ¢f Suresi, 56'),
('EÄŸer Allah birini severse onu dertlerle sÄ±nar.', 'Hadis-i Åerif'),
('Ya Rabbi, gÃ¶nlÃ¼me sÃ¼kÃ»net, kalbime inÅŸirah ver.', 'Hz. Musa''nÄ±n DuasÄ± (TÃ¢hÃ¢: 25)'),
('Ne kadar yorulduÄŸunu anlayan bir Rabbin var. Sabret.', 'Anonim'),
('Kalbinizi Allah(c.c)''a teslim ederseniz, O(c.c) onu en gÃ¼zel kaba koyar.', 'Hz. Ã–mer (r.a)'),
('Bana Allah yeter, ondan baÅŸka ilah yoktur.', 'Tevbe Suresi, 129'),
('Rabbin seni asla unutmaz.', 'Meryem Suresi, 64'),
('Ä°mtihandÄ±r; geÃ§er, biter, gider... AsÄ±l mesele, sabretmek ve ÅŸÃ¼kretmektir.', 'Anonim'),
('Senin gÃ¼cÃ¼n Allah''a tam manasÄ±yla gÃ¼venmektir.', 'Hz. Ali (r.a)'),
('DuasÄ± reddedilemeyecek olan mazlumun ahÄ±ndan sakÄ±nÄ±n.', 'Hadis-i Åerif'),
('O, kullarÄ±ndan duayÄ± kabul eden ve kÃ¶tÃ¼lÃ¼kleri affedendir.', 'ÅÃ»rÃ¢ Suresi, 25'),
('Gelecek umutla doludur Ã§Ã¼nkÃ¼ O "KÃ¼n feyekÃ¼n" Rabbidir.', 'Anonim'),
('Ey kalpleri evirip Ã§eviren Allah''Ä±m! Kalbimi dinin Ã¼zerinde sabit kÄ±l.', 'Hadis-i Åerif (Dua)'),
('Ne olursa olsun, gÃ¼neÅŸ her gÃ¼n yeniden doÄŸar; umutlar O''nun inayetiyle yeÅŸerir.', 'Mevlana'),
('O (Allah), gizlinin gizlisini de bilir.', 'TÃ¢hÃ¢ Suresi, 7'),
('Ey iman edenler! SabÄ±r ve namaz ile Allah''tan yardÄ±m isteyin.', 'Bakara Suresi, 153'),
('Gidecek bir kapÄ±nÄ±z yoksa, ellerinizi Rabbinize aÃ§Ä±n.', 'Anonim'),
('Kainatta tesadÃ¼f yoktur, her ÅŸey ince bir tevafuk esedir.', 'Ä°slam Felsefesi'),
('Allah''a dayandÄ±m, hikmetine ram oldum.', 'Anonim'),
('Allah katÄ±nda en sevimli amel, az da olsa sÃ¼rekli olanÄ±dÄ±r.', 'Hadis-i Åerif'),
('HaksÄ±zlÄ±k karÅŸÄ±sÄ±nda susan dilsiz ÅŸeytandÄ±r.', 'Hadis-i Åerif'),
('Nereye kaÃ§arsan kaÃ§, O''ndan yine O''na kaÃ§Ä±yorsun.', 'Hz. Ali (r.a)'),
('GÃ¼nahÄ±nÄ± gizleyen ile gÃ¼nahÄ± baÄŸÄ±ÅŸlanan arasÄ±nda sadece tÃ¶vbe vardÄ±r.', 'TÃ¶vbe KavramÄ±'),
('Allah, hiÃ§ kimseye gÃ¼cÃ¼nÃ¼n yeteceÄŸinden baÅŸka yÃ¼k yÃ¼klemez.', 'Bakara Suresi, 286'),
('DÃ¼nya fani, Ã¶lÃ¼m ani. Vakit varken secdeye kapan.', 'Anonim'),
('SabÄ±r, acÄ± bir meyvedir fakat ÅŸifasÄ± sonsuzdur.', 'Hz. Hasan (r.a)'),
('YalnÄ±zca sana kulluk eder ve yalnÄ±zca senden yardÄ±m dileriz.', 'Fatiha Suresi, 5'),
('Nasibin; sen ona gitmesen de Allah onu sana getirir.', 'Hz. Ali (r.a)'),
('Bir iÅŸe baÅŸladÄ±ÄŸÄ±n zaman Allah''a tevekkÃ¼l et.', 'Ã‚l-i Ä°mran Suresi, 159'),
('Bazen gÃ¶zyaÅŸlarÄ±, kelimelerin sÃ¶yleyemediÄŸi en gÃ¼zel duadÄ±r.', 'Anonim'),
('SÄ±kÄ±ntÄ±lar misafirdir, bir gÃ¼n giderler; geriye ecrin ve sabrÄ±n kalÄ±r.', 'Mevlana'),
('GÃ¶zÃ¼n gÃ¶rdÃ¼ÄŸÃ¼ fani, gÃ¶nlÃ¼n gÃ¶rdÃ¼ÄŸÃ¼ bakidir.', 'Tasavvuf'),
('KullarÄ±m sana beni sorduklarÄ±nda bilsinler ki, ben Ã§ok yakÄ±nÄ±m.', 'Bakara Suresi, 186'),
('Mevsimler nasÄ±l deÄŸiÅŸiyorsa, dertler de Ã¶yle deÄŸiÅŸir. Yeter ki O''na tutun.', 'Anonim'),
('AÄŸaÃ§ dalÄ±nda kuÅŸ dÃ¼ÅŸmekten korkmaz, Ã§Ã¼nkÃ¼ gÃ¼vendiÄŸi dal deÄŸil, kendi kanatlarÄ±dÄ±r. MÃ¼min de ÅŸarta deÄŸil, Rabbe gÃ¼venir.', 'KÄ±ssa'),
('Biz seni ancak alemlere rahmet olarak gÃ¶nderdik.', 'EnbiyÃ¢ Suresi, 107'),
('Kalbin kÄ±rÄ±ldÄ± diye Ã¼zÃ¼lme, Allah kÄ±rÄ±k kalplerdedir.', 'Hadis-i Kudsi Yorumu'),
('Cennetin en gÃ¼zel Ã§iÃ§eÄŸi, gecenin bir yarÄ±sÄ± Rabbe dÃ¶kÃ¼len gÃ¶zyaÅŸÄ±dÄ±r.', 'Anonim'),
('DÃ¼nyada rahat, ahirette saadettir gerÃ§ek olan.', 'Anonim'),
('O her gÃ¼n yeni bir iÅŸtedir.', 'RahmÃ¢n Suresi, 29'),
('Dua, eÅŸyayÄ± sarsar, yeri yerinden oynatÄ±r ve bulutlarÄ± rahmete dÃ¶ndÃ¼rÃ¼r.', 'Ä°slami Ã–zdeyiÅŸ'),
('Ä°mtihan senin gÃ¼cÃ¼nÃ¼ Ã¶lÃ§mek iÃ§in deÄŸil, acziyetini sana gÃ¶stermek iÃ§indir.', 'Tasavvufi Yorum'),
('Allah''Ä±n rÄ±zasÄ± ve merhameti her zaman Ã¶fkeden Ã¼stÃ¼ndÃ¼r.', 'Hadis-i Åerif'),
('VerdiÄŸine de vermediÄŸine de ÅŸÃ¼kÃ¼rler olsun Ya Rab.', 'Hz. Ebu Bekir (r.a)'),
('TebessÃ¼m sadakadÄ±r.', 'Hadis-i Åerif'),
('GÃ¼l gibi olmak istersen, topraÄŸa tohum ol; Allah''a tam teslim ol.', 'Mevlana'),
('Dua ile aÃ§Ä±lan kapÄ±lar, ÅŸeytanÄ±n gÃ¼cÃ¼yle kapanmaz.', 'Anonim'),
('O ne eylerse gÃ¼zel eyler.', 'Erzurumlu Ä°brahim HakkÄ±');
-- 100 Adet 'GÃ¼nÃ¼n Ayeti ve Hadisi' (daily_content) Ä°Ã§eriÄŸi
INSERT INTO daily_content (type, arabic_text, turkish_text, source) VALUES
-- AYETLER (50)
('ayet', 'Ø¥ÙÙ†ÙÙ‘ Ø§Ù„Ù„ÙÙ‘Ù‡Ù Ù…ÙØ¹Ù Ø§Ù„ØµÙÙ‘Ø§Ø¨ÙØ±ÙÙŠÙ†Ù', 'ÅÃ¼phesiz Allah sabredenlerle beraberdir.', 'Bakara Suresi, 153'),
('ayet', 'ÙÙØ§Ø°Ù’ÙƒÙØ±ÙÙˆÙ†ÙÙŠ Ø£ÙØ°Ù’ÙƒÙØ±Ù’ÙƒÙÙ…Ù’ ÙˆÙØ§Ø´Ù’ÙƒÙØ±ÙÙˆØ§ Ù„ÙÙŠ ÙˆÙÙ„ÙØ§ ØªÙÙƒÙ’ÙÙØ±ÙÙˆÙ†Ù', 'Ã–yleyse beni anÄ±n ki ben de sizi anayÄ±m. Bana ÅŸÃ¼kredin, sakÄ±n nankÃ¶rlÃ¼k etmeyin.', 'Bakara Suresi, 152'),
('ayet', 'ÙˆÙÙ…ÙØ§ ÙƒÙØ§Ù†Ù Ø§Ù„Ù„ÙÙ‘Ù‡Ù Ù„ÙÙŠÙØ¹ÙØ°ÙÙ‘Ø¨ÙÙ‡ÙÙ…Ù’ ÙˆÙØ£ÙÙ†Ù’ØªÙ ÙÙÙŠÙ‡ÙÙ…Ù’', 'Sen onlarÄ±n iÃ§indeyken Allah onlara azap edecek deÄŸildir.', 'EnfÃ¢l Suresi, 33'),
('ayet', 'ÙˆÙÙ„ÙØ³ÙÙˆÙ’ÙÙ ÙŠÙØ¹Ù’Ø·ÙÙŠÙƒÙ Ø±ÙØ¨ÙÙ‘ÙƒÙ ÙÙØªÙØ±Ù’Ø¶ÙÙ‰', 'Rabbin sana verecek ve sen razÄ± olacaksÄ±n.', 'DuhÃ¢ Suresi, 5'),
('ayet', 'Ù‚ÙÙ„Ù’ ÙŠÙØ§ Ø¹ÙØ¨ÙØ§Ø¯ÙÙŠÙ Ø§Ù„ÙÙ‘Ø°ÙÙŠÙ†Ù Ø£ÙØ³Ù’Ø±ÙÙÙÙˆØ§ Ø¹ÙÙ„ÙÙ‰ Ø£ÙÙ†Ù’ÙÙØ³ÙÙ‡ÙÙ…Ù’ Ù„ÙØ§ ØªÙÙ‚Ù’Ù†ÙØ·ÙÙˆØ§ Ù…ÙÙ†Ù’ Ø±ÙØ­Ù’Ù…ÙØ©Ù Ø§Ù„Ù„ÙÙ‘Ù‡Ù', 'De ki: Ey kendi nefisleri aleyhine haddi aÅŸan kullarÄ±m! Allahâ€™Ä±n rahmetinden Ã¼mit kesmeyin.', 'ZÃ¼mer Suresi, 53'),
('ayet', 'ÙˆÙØ§Ø³Ù’ØªÙØ¹ÙÙŠÙ†ÙÙˆØ§ Ø¨ÙØ§Ù„ØµÙÙ‘Ø¨Ù’Ø±Ù ÙˆÙØ§Ù„ØµÙÙ‘Ù„ÙØ§Ø©Ù', 'SabÄ±r ve namaz ile Allah''tan yardÄ±m isteyin.', 'Bakara Suresi, 45'),
('ayet', 'ÙˆÙØ±ÙØ­Ù’Ù…ÙØªÙÙŠ ÙˆÙØ³ÙØ¹ÙØªÙ’ ÙƒÙÙ„ÙÙ‘ Ø´ÙÙŠÙ’Ø¡Ù', 'Benim rahmetim her ÅŸeyi kuÅŸatmÄ±ÅŸtÄ±r.', 'A''rÃ¢f Suresi, 156'),
('ayet', 'Ø£ÙÙ„ÙØ§ Ø¨ÙØ°ÙÙƒÙ’Ø±Ù Ø§Ù„Ù„ÙÙ‘Ù‡Ù ØªÙØ·Ù’Ù…ÙØ¦ÙÙ†ÙÙ‘ Ø§Ù„Ù’Ù‚ÙÙ„ÙÙˆØ¨Ù', 'Haberiniz olsun; kalpler ancak Allah''Ä± zikretmekle huzur bulur.', 'Ra''d Suresi, 28'),
('ayet', 'Ø¥ÙÙ†ÙÙ‘ Ù…ÙØ¹Ù Ø§Ù„Ù’Ø¹ÙØ³Ù’Ø±Ù ÙŠÙØ³Ù’Ø±Ù‹Ø§', 'Elbette her zorluÄŸun yanÄ±nda bir kolaylÄ±k vardÄ±r.', 'Ä°nÅŸirah Suresi, 6'),
('ayet', 'ÙˆÙØ§Ù„Ù„ÙÙ‘Ù‡Ù ÙŠÙØ­ÙØ¨ÙÙ‘ Ø§Ù„Ù’Ù…ÙØ­Ù’Ø³ÙÙ†ÙÙŠÙ†Ù', 'Allah, iyilik edenleri sever.', 'Ã‚l-i Ä°mrÃ¢n Suresi, 134'),
('ayet', 'ÙˆÙÙ…ÙÙ†Ù’ ÙŠÙØªÙÙ‘Ù‚Ù Ø§Ù„Ù„ÙÙ‘Ù‡Ù ÙŠÙØ¬Ù’Ø¹ÙÙ„Ù’ Ù„ÙÙ‡Ù Ù…ÙØ®Ù’Ø±ÙØ¬Ù‹Ø§', 'Kim Allah''a karÅŸÄ± gelmekten sakÄ±nÄ±rsa, Allah ona bir Ã§Ä±kÄ±ÅŸ yolu aÃ§ar.', 'TalÃ¢k Suresi, 2'),
('ayet', 'ÙˆÙÙŠÙØ±Ù’Ø²ÙÙ‚Ù’Ù‡Ù Ù…ÙÙ†Ù’ Ø­ÙÙŠÙ’Ø«Ù Ù„ÙØ§ ÙŠÙØ­Ù’ØªÙØ³ÙØ¨Ù', 'Ve onu ummadÄ±ÄŸÄ± yerden rÄ±zÄ±klandÄ±rÄ±r.', 'TalÃ¢k Suresi, 3'),
('ayet', 'Ø¥ÙÙ†ÙÙ‘ Ø§Ù„Ù„ÙÙ‘Ù‡Ù ÙƒÙØ§Ù†Ù Ø¹ÙÙ„ÙÙŠÙ’ÙƒÙÙ…Ù’ Ø±ÙÙ‚ÙÙŠØ¨Ù‹Ø§', 'ÅÃ¼phesiz Allah, sizin Ã¼zerinizde gÃ¶zetleyicidir.', 'NisÃ¢ Suresi, 1'),
('ayet', 'Ù„ÙØ¦ÙÙ†Ù’ Ø´ÙÙƒÙØ±Ù’ØªÙÙ…Ù’ Ù„ÙØ£ÙØ²ÙÙŠØ¯ÙÙ†ÙÙ‘ÙƒÙÙ…Ù’', 'EÄŸer ÅŸÃ¼krederseniz, size nimetimi mutlaka artÄ±rÄ±rÄ±m.', 'Ä°brahim Suresi, 7'),
('ayet', 'ÙˆÙÙ‡ÙÙˆÙ Ù…ÙØ¹ÙÙƒÙÙ…Ù’ Ø£ÙÙŠÙ’Ù†Ù Ù…ÙØ§ ÙƒÙÙ†Ù’ØªÙÙ…Ù’', 'Nerede olursanÄ±z olun, O sizinle beraberdir.', 'HadÃ®d Suresi, 4'),
('ayet', 'Ø±ÙØ¨ÙÙ‘Ù†ÙØ§ Ø¢ØªÙÙ†ÙØ§ ÙÙÙŠ Ø§Ù„Ø¯ÙÙ‘Ù†Ù’ÙŠÙØ§ Ø­ÙØ³ÙÙ†ÙØ©Ù‹ ÙˆÙÙÙÙŠ Ø§Ù„Ù’Ø¢Ø®ÙØ±ÙØ©Ù Ø­ÙØ³ÙÙ†ÙØ©Ù‹ ÙˆÙÙ‚ÙÙ†ÙØ§ Ø¹ÙØ°ÙØ§Ø¨Ù Ø§Ù„Ù†ÙÙ‘Ø§Ø±Ù', 'Rabbimiz! Bize dÃ¼nyada da iyilik ver, ahirette de iyilik ver ve bizi ateÅŸ azabÄ±ndan koru.', 'Bakara Suresi, 201'),
('ayet', 'Ø­ÙØ³Ù’Ø¨ÙÙ†ÙØ§ Ø§Ù„Ù„ÙÙ‘Ù‡Ù ÙˆÙÙ†ÙØ¹Ù’Ù…Ù Ø§Ù„Ù’ÙˆÙÙƒÙÙŠÙ„Ù', 'Allah bize yeter; O, ne gÃ¼zel vekildir.', 'Ã‚l-i Ä°mrÃ¢n Suresi, 173'),
('ayet', 'Ù„ÙØ§ ÙŠÙÙƒÙÙ„ÙÙ‘ÙÙ Ø§Ù„Ù„ÙÙ‘Ù‡Ù Ù†ÙÙÙ’Ø³Ù‹Ø§ Ø¥ÙÙ„ÙÙ‘Ø§ ÙˆÙØ³Ù’Ø¹ÙÙ‡ÙØ§', 'Allah, hiÃ§ kimseye gÃ¼cÃ¼nÃ¼n yettiÄŸinden baÅŸka yÃ¼k yÃ¼klemez.', 'Bakara Suresi, 286'),
('ayet', 'Ø¥ÙÙ†ÙÙ‘ Ø£ÙÙƒÙ’Ø±ÙÙ…ÙÙƒÙÙ…Ù’ Ø¹ÙÙ†Ù’Ø¯Ù Ø§Ù„Ù„ÙÙ‘Ù‡Ù Ø£ÙØªÙ’Ù‚ÙØ§ÙƒÙÙ…Ù’', 'Allah katÄ±nda en deÄŸerli olanÄ±nÄ±z, Oâ€™na karÅŸÄ± gelmekten en Ã§ok sakÄ±nanÄ±nÄ±zdÄ±r.', 'HucurÃ¢t Suresi, 13'),
('ayet', 'ÙˆÙÙ‚ÙÙ„Ù’ Ø±ÙØ¨ÙÙ‘ Ø²ÙØ¯Ù’Ù†ÙÙŠ Ø¹ÙÙ„Ù’Ù…Ù‹Ø§', 'De ki: Rabbim, ilmimi artÄ±r.', 'TÃ¢hÃ¢ Suresi, 114'),
('ayet', 'ÙŠÙØ§ Ø£ÙÙŠÙÙ‘Ù‡ÙØ§ Ø§Ù„ÙÙ‘Ø°ÙÙŠÙ†Ù Ø¢Ù…ÙÙ†ÙÙˆØ§ Ø§ØªÙÙ‘Ù‚ÙÙˆØ§ Ø§Ù„Ù„ÙÙ‘Ù‡Ù', 'Ey iman edenler! Allah''tan sakÄ±nÄ±n.', 'AhzÃ¢b Suresi, 70'),
('ayet', 'ÙˆÙØ£ÙÙ†Ù’ Ù„ÙÙŠÙ’Ø³Ù Ù„ÙÙ„Ù’Ø¥ÙÙ†Ù’Ø³ÙØ§Ù†Ù Ø¥ÙÙ„ÙÙ‘Ø§ Ù…ÙØ§ Ø³ÙØ¹ÙÙ‰', 'Ä°nsan iÃ§in ancak Ã§alÄ±ÅŸtÄ±ÄŸÄ±nÄ±n karÅŸÄ±lÄ±ÄŸÄ± vardÄ±r.', 'Necm Suresi, 39'),
('ayet', 'ÙˆÙØ§Ù„Ù„ÙÙ‘Ù‡Ù Ø¨ÙÙ…ÙØ§ ØªÙØ¹Ù’Ù…ÙÙ„ÙÙˆÙ†Ù Ø¨ÙØµÙÙŠØ±ÙŒ', 'Allah, bÃ¼tÃ¼n yaptÄ±klarÄ±nÄ±zÄ± hakkÄ±yla gÃ¶rendir.', 'Bakara Suresi, 110'),
('ayet', 'ÙˆÙØ¹ÙØ³ÙÙ‰ Ø£ÙÙ†Ù’ ØªÙÙƒÙ’Ø±ÙÙ‡ÙÙˆØ§ Ø´ÙÙŠÙ’Ø¦Ù‹Ø§ ÙˆÙÙ‡ÙÙˆÙ Ø®ÙÙŠÙ’Ø±ÙŒ Ù„ÙÙƒÙÙ…Ù’', 'Sizin iÃ§in hayÄ±rlÄ± olduÄŸu halde bir ÅŸeyi sevmiyor olabilirsiniz.', 'Bakara Suresi, 216'),
('ayet', 'ÙÙØ§Ø¯Ù’Ø¹ÙÙˆØ§ Ø§Ù„Ù„ÙÙ‘Ù‡Ù Ù…ÙØ®Ù’Ù„ÙØµÙÙŠÙ†Ù Ù„ÙÙ‡Ù Ø§Ù„Ø¯ÙÙ‘ÙŠÙ†Ù', 'Siz dini Allah''a has kÄ±larak O''na dua edin.', 'MÃ¼â€™min Suresi, 14'),
('ayet', 'ÙˆÙÙ…ÙØ§ ØªÙÙˆÙ’ÙÙÙŠÙ‚ÙÙŠ Ø¥ÙÙ„ÙÙ‘Ø§ Ø¨ÙØ§Ù„Ù„ÙÙ‘Ù‡Ù', 'Benim baÅŸarÄ±m ancak Allah''Ä±n yardÄ±mÄ±yladÄ±r.', 'HÃ»d Suresi, 88'),
('ayet', 'Ø£ÙÙ„ÙÙŠÙ’Ø³Ù Ø§Ù„Ù„ÙÙ‘Ù‡Ù Ø¨ÙÙƒÙØ§ÙÙ Ø¹ÙØ¨Ù’Ø¯ÙÙ‡Ù', 'Allah kuluna kÃ¢fi deÄŸil midir?', 'ZÃ¼mer Suresi, 36'),
('ayet', 'ÙˆÙØ§Ø¹Ù’ØªÙØµÙÙ…ÙÙˆØ§ Ø¨ÙØ­ÙØ¨Ù’Ù„Ù Ø§Ù„Ù„ÙÙ‘Ù‡Ù Ø¬ÙÙ…ÙÙŠØ¹Ù‹Ø§ ÙˆÙÙ„ÙØ§ ØªÙÙÙØ±ÙÙ‘Ù‚ÙÙˆØ§', 'Hep birlikte Allah''Ä±n ipine sÄ±msÄ±kÄ± sarÄ±lÄ±n; parÃ§alanÄ±p bÃ¶lÃ¼nmeyin.', 'Ã‚l-i Ä°mrÃ¢n Suresi, 103'),
('ayet', 'ÙƒÙÙ„ÙÙ‘ Ù†ÙÙÙ’Ø³Ù Ø°ÙØ§Ø¦ÙÙ‚ÙØ©Ù Ø§Ù„Ù’Ù…ÙÙˆÙ’ØªÙ', 'Her can Ã¶lÃ¼mÃ¼ tadacaktÄ±r.', 'Ã‚l-i Ä°mrÃ¢n Suresi, 185'),
('ayet', 'Ø¥ÙÙ†ÙÙ‘ Ù‡ÙØ°ÙØ§ Ø§Ù„Ù’Ù‚ÙØ±Ù’Ø¢Ù†Ù ÙŠÙÙ‡Ù’Ø¯ÙÙŠ Ù„ÙÙ„ÙÙ‘ØªÙÙŠ Ù‡ÙÙŠÙ Ø£ÙÙ‚Ù’ÙˆÙÙ…Ù', 'ÅÃ¼phesiz bu Kur''an, en doÄŸru olan yola iletir.', 'Ä°srÃ¢ Suresi, 9'),
('ayet', 'ÙˆÙØ£ÙÙ‚ÙÙŠÙ…ÙÙˆØ§ Ø§Ù„ØµÙÙ‘Ù„ÙØ§Ø©Ù ÙˆÙØ¢ØªÙÙˆØ§ Ø§Ù„Ø²ÙÙ‘ÙƒÙØ§Ø©Ù', 'NamazÄ± kÄ±lÄ±n, zekatÄ± verin.', 'Bakara Suresi, 43'),
('ayet', 'ÙˆÙØ®ÙÙ„ÙÙ‚Ù Ø§Ù„Ù’Ø¥ÙÙ†Ù’Ø³ÙØ§Ù†Ù Ø¶ÙØ¹ÙÙŠÙÙ‹Ø§', 'Ä°nsan zayÄ±f olarak yaratÄ±lmÄ±ÅŸtÄ±r.', 'NisÃ¢ Suresi, 28'),
('ayet', 'ÙŠÙØ¯ÙØ¨ÙÙ‘Ø±Ù Ø§Ù„Ù’Ø£ÙÙ…Ù’Ø±Ù', 'O, her iÅŸi dÃ¼zenleyip yÃ¶netir.', 'Yunus Suresi, 31'),
('ayet', 'ÙˆÙØ§Ù„Ù„ÙÙ‘Ù‡Ù ÙŠÙØ¹Ù’Ù„ÙÙ…Ù ÙˆÙØ£ÙÙ†Ù’ØªÙÙ…Ù’ Ù„ÙØ§ ØªÙØ¹Ù’Ù„ÙÙ…ÙÙˆÙ†Ù', 'Allah bilir, siz bilmezsiniz.', 'Bakara Suresi, 216'),
('ayet', 'Ø¥ÙÙ†ÙÙ‘ Ø±ÙØ¨ÙÙ‘ÙŠ Ù‚ÙØ±ÙÙŠØ¨ÙŒ Ù…ÙØ¬ÙÙŠØ¨ÙŒ', 'ÅÃ¼phesiz Rabbim Ã§ok yakÄ±ndÄ±r, dualarÄ± kabul edendir.', 'HÃ»d Suresi, 61'),
('ayet', 'ÙˆÙÙ‚ÙÙˆÙ„ÙÙˆØ§ Ù„ÙÙ„Ù†ÙÙ‘Ø§Ø³Ù Ø­ÙØ³Ù’Ù†Ù‹Ø§', 'Ä°nsanlara gÃ¼zel sÃ¶z sÃ¶yleyin.', 'Bakara Suresi, 83'),
('ayet', 'Ø§Ù„Ù’Ø­ÙÙ…Ù’Ø¯Ù Ù„ÙÙ„ÙÙ‘Ù‡Ù Ø±ÙØ¨ÙÙ‘ Ø§Ù„Ù’Ø¹ÙØ§Ù„ÙÙ…ÙÙŠÙ†Ù', 'Hamd, alemlerin Rabbi Allah''a mahsustur.', 'Fatiha Suresi, 2'),
('ayet', 'Ø§Ù‡Ù’Ø¯ÙÙ†ÙØ§ Ø§Ù„ØµÙÙ‘Ø±ÙØ§Ø·Ù Ø§Ù„Ù’Ù…ÙØ³Ù’ØªÙÙ‚ÙÙŠÙ…Ù', 'Bizi doÄŸru yola ilet.', 'Fatiha Suresi, 6'),
('ayet', 'ÙˆÙØ§Ù„Ù„ÙÙ‘Ù‡Ù Ø¹ÙØ²ÙÙŠØ²ÙŒ Ø°ÙÙˆ Ø§Ù†Ù’ØªÙÙ‚ÙØ§Ù…Ù', 'Allah, mutlak gÃ¼Ã§ sahibidir, intikam sahibidir.', 'Ã‚l-i Ä°mrÃ¢n Suresi, 4'),
('ayet', 'Ø¥ÙÙ†ÙÙ‘ Ø§Ù„Ø¯ÙÙ‘ÙŠÙ†Ù Ø¹ÙÙ†Ù’Ø¯Ù Ø§Ù„Ù„ÙÙ‘Ù‡Ù Ø§Ù„Ù’Ø¥ÙØ³Ù’Ù„ÙØ§Ù…Ù', 'Allah katÄ±nda hak din, Ä°slam''dÄ±r.', 'Ã‚l-i Ä°mrÃ¢n Suresi, 19'),
('ayet', 'ÙˆÙØªÙÙˆÙÙƒÙÙ‘Ù„Ù’ Ø¹ÙÙ„ÙÙ‰ Ø§Ù„Ù’Ø­ÙÙŠÙÙ‘ Ø§Ù„ÙÙ‘Ø°ÙÙŠ Ù„ÙØ§ ÙŠÙÙ…ÙÙˆØªÙ', 'Sen, Ã¶lÃ¼msÃ¼z ve daima diri olan Allah''a tevekkÃ¼l et.', 'FurkÃ¢n Suresi, 58'),
('ayet', 'Ø¥ÙÙ†ÙÙ‘Ù…ÙØ§ Ø§Ù„Ù’Ù…ÙØ¤Ù’Ù…ÙÙ†ÙÙˆÙ†Ù Ø¥ÙØ®Ù’ÙˆÙØ©ÙŒ', 'MÃ¼minler ancak kardeÅŸtirler.', 'HucurÃ¢t Suresi, 10'),
('ayet', 'ÙˆÙÙ„ÙØ§ ØªÙØ­Ù’Ø³ÙØ¨ÙÙ†ÙÙ‘ Ø§Ù„Ù„ÙÙ‘Ù‡Ù ØºÙØ§ÙÙÙ„Ù‹Ø§ Ø¹ÙÙ…ÙÙ‘Ø§ ÙŠÙØ¹Ù’Ù…ÙÙ„Ù Ø§Ù„Ø¸ÙÙ‘Ø§Ù„ÙÙ…ÙÙˆÙ†Ù', 'Allah''Ä± zalimlerin yaptÄ±klarÄ±ndan habersiz sanma.', 'Ä°brahim Suresi, 42'),
('ayet', 'Ø³ÙÙ„ÙØ§Ù…ÙŒ Ù‚ÙÙˆÙ’Ù„Ù‹Ø§ Ù…ÙÙ†Ù’ Ø±ÙØ¨ÙÙ‘ Ø±ÙØ­ÙÙŠÙ…Ù', 'Ã‡ok merhametli olan Rab''den onlara sÃ¶zlÃ¼ olarak selam gelir.', 'YÃ¢sÃ®n Suresi, 58'),
('ayet', 'ÙˆÙØ³ÙÙŠÙØ¬Ù’Ø²ÙÙŠ Ø§Ù„Ù„ÙÙ‘Ù‡Ù Ø§Ù„Ø´ÙÙ‘Ø§ÙƒÙØ±ÙÙŠÙ†Ù', 'Allah ÅŸÃ¼kredenleri mÃ¼kafatlandÄ±racaktÄ±r.', 'Ã‚l-i Ä°mrÃ¢n Suresi, 144'),
('ayet', 'Ø¥ÙÙ†ÙÙ‘ Ø§Ù„Ù’Ø­ÙØ³ÙÙ†ÙØ§ØªÙ ÙŠÙØ°Ù’Ù‡ÙØ¨Ù’Ù†Ù Ø§Ù„Ø³ÙÙ‘ÙŠÙÙ‘Ø¦ÙØ§ØªÙ', 'Iyilikler, kÃ¶tÃ¼lÃ¼kleri giderir.', 'HÃ»d Suresi, 114'),
('ayet', 'ÙˆÙÙ„ÙØ§ ØªÙÙÙ’Ø³ÙØ¯ÙÙˆØ§ ÙÙÙŠ Ø§Ù„Ù’Ø£ÙØ±Ù’Ø¶Ù Ø¨ÙØ¹Ù’Ø¯Ù Ø¥ÙØµÙ’Ù„ÙØ§Ø­ÙÙ‡ÙØ§', 'DÃ¼zene sokulduktan sonra yeryÃ¼zÃ¼nde bozgunculuk yapmayÄ±n.', 'A''rÃ¢f Suresi, 56'),
('ayet', 'Ø¥ÙÙ†ÙÙ‘ Ø§Ù„Ù„ÙÙ‘Ù‡Ù ÙŠÙØ£Ù’Ù…ÙØ±Ù Ø¨ÙØ§Ù„Ù’Ø¹ÙØ¯Ù’Ù„Ù ÙˆÙØ§Ù„Ù’Ø¥ÙØ­Ù’Ø³ÙØ§Ù†Ù', 'Muhakkak ki Allah, adaleti ve iyiliÄŸi emreder.', 'Nahl Suresi, 90'),
('ayet', 'ÙˆÙÙ…ÙØ§ Ø§Ù„Ù’Ø­ÙÙŠÙØ§Ø©Ù Ø§Ù„Ø¯ÙÙ‘Ù†Ù’ÙŠÙØ§ Ø¥ÙÙ„ÙÙ‘Ø§ Ù…ÙØªÙØ§Ø¹Ù Ø§Ù„Ù’ØºÙØ±ÙÙˆØ±Ù', 'DÃ¼nya hayatÄ±, aldatÄ±cÄ± bir metadan baÅŸka bir ÅŸey deÄŸildir.', 'Ã‚l-i Ä°mrÃ¢n Suresi, 185'),
('ayet', 'ÙÙØ¨ÙØ£ÙÙŠÙÙ‘ Ø¢Ù„ÙØ§Ø¡Ù Ø±ÙØ¨ÙÙ‘ÙƒÙÙ…ÙØ§ ØªÙÙƒÙØ°ÙÙ‘Ø¨ÙØ§Ù†Ù', 'O halde Rabbinizin hangi nimetlerini yalanlayabilirsiniz?', 'RahmÃ¢n Suresi, 13'),


-- HADÄ°SLER (50)
('hadis', 'Ù…ÙÙ†Ù’ ØµÙÙ…ÙØªÙ Ù†ÙØ¬ÙØ§', 'Susan kurtulmuÅŸtur.', 'Tirmizi'),
('hadis', 'Ø§Ù„Ø¯ÙÙ‘ÙŠÙ†Ù Ø§Ù„Ù†ÙÙ‘ØµÙÙŠØ­ÙØ©Ù', 'Din samimiyettir (nasihattir).', 'MÃ¼slim'),
('hadis', 'Ø¥ÙÙ†ÙÙ‘Ù…ÙØ§ Ø§Ù„Ù’Ø£ÙØ¹Ù’Ù…ÙØ§Ù„Ù Ø¨ÙØ§Ù„Ù†ÙÙ‘ÙŠÙÙ‘Ø§ØªÙ', 'Ameller ancak niyetlere gÃ¶redir.', 'Buhari'),
('hadis', 'Ø®ÙÙŠÙ’Ø±ÙÙƒÙÙ…Ù’ Ù…ÙÙ†Ù’ ØªÙØ¹ÙÙ„ÙÙ‘Ù…Ù Ø§Ù„Ù’Ù‚ÙØ±Ù’Ø¢Ù†Ù ÙˆÙØ¹ÙÙ„ÙÙ‘Ù…ÙÙ‡Ù', 'Sizin en hayÄ±rlÄ±nÄ±z Kurâ€™anâ€™Ä± Ã¶ÄŸrenen ve Ã¶ÄŸretendir.', 'Buhari'),
('hadis', 'Ø§Ù„Ø¯ÙÙ‘Ø§Ù„ÙÙ‘ Ø¹ÙÙ„ÙÙ‰ Ø§Ù„Ù’Ø®ÙÙŠÙ’Ø±Ù ÙƒÙÙÙØ§Ø¹ÙÙ„ÙÙ‡Ù', 'Hayra vesile olan, o hayrÄ± iÅŸleyen gibidir.', 'Tirmizi'),
('hadis', 'Ù…ÙÙ†Ù’ Ù„ÙØ§ ÙŠÙØ±Ù’Ø­ÙÙ…Ù Ø§Ù„Ù†ÙÙ‘Ø§Ø³Ù Ù„ÙØ§ ÙŠÙØ±Ù’Ø­ÙÙ…Ù’Ù‡Ù Ø§Ù„Ù„ÙÙ‘Ù‡Ù', 'Ä°nsanlara merhamet etmeyene Allah da merhamet etmez.', 'MÃ¼slim'),
('hadis', 'Ø§Ù„Ù’Ù…ÙØ³Ù’Ù„ÙÙ…Ù Ù…ÙÙ†Ù’ Ø³ÙÙ„ÙÙ…Ù Ø§Ù„Ù’Ù…ÙØ³Ù’Ù„ÙÙ…ÙÙˆÙ†Ù Ù…ÙÙ†Ù’ Ù„ÙØ³ÙØ§Ù†ÙÙ‡Ù ÙˆÙÙŠÙØ¯ÙÙ‡Ù', 'MÃ¼slÃ¼man, diÄŸer MÃ¼slÃ¼manlarÄ±n onun elinden ve dilinden gÃ¼vende olduÄŸu kimsedir.', 'Buhari'),
('hadis', 'Ø§Ù„Ø·ÙÙ‘Ù‡ÙÙˆØ±Ù Ø´ÙØ·Ù’Ø±Ù Ø§Ù„Ù’Ø¥ÙÙŠÙ…ÙØ§Ù†Ù', 'Temizlik imanÄ±n yarÄ±sÄ±dÄ±r.', 'MÃ¼slim'),
('hadis', 'ØªÙØ¨ÙØ³ÙÙ‘Ù…ÙÙƒÙ ÙÙÙŠ ÙˆÙØ¬Ù’Ù‡Ù Ø£ÙØ®ÙÙŠÙƒÙ Ù„ÙÙƒÙ ØµÙØ¯ÙÙ‚ÙØ©ÙŒ', 'KardeÅŸinin yÃ¼zÃ¼ne tebessÃ¼m etmen bir sadakadÄ±r.', 'Tirmizi'),
('hadis', 'ÙŠÙØ³ÙÙ‘Ø±ÙÙˆØ§ ÙˆÙÙ„ÙØ§ ØªÙØ¹ÙØ³ÙÙ‘Ø±ÙÙˆØ§ØŒ ÙˆÙØ¨ÙØ´ÙÙ‘Ø±ÙÙˆØ§ ÙˆÙÙ„ÙØ§ ØªÙÙ†ÙÙÙÙ‘Ø±ÙÙˆØ§', 'KolaylaÅŸtÄ±rÄ±n, zorlaÅŸtÄ±rmayÄ±n; mÃ¼jdeleyin, nefret ettirmeyin.', 'Buhari'),
('hadis', 'Ù„ÙØ§ ÙŠÙØ¤Ù’Ù…ÙÙ†Ù Ø£ÙØ­ÙØ¯ÙÙƒÙÙ…Ù’ Ø­ÙØªÙÙ‘Ù‰ ÙŠÙØ­ÙØ¨ÙÙ‘ Ù„ÙØ£ÙØ®ÙÙŠÙ‡Ù Ù…ÙØ§ ÙŠÙØ­ÙØ¨ÙÙ‘ Ù„ÙÙ†ÙÙÙ’Ø³ÙÙ‡Ù', 'HiÃ§biriniz kendi nefsi iÃ§in istediÄŸini kardeÅŸi iÃ§in de istemedikÃ§e tam iman etmiÅŸ olamaz.', 'Buhari'),
('hadis', 'Ø§Ù„Ù’Ø¬ÙÙ†ÙÙ‘Ø©Ù ØªÙØ­Ù’ØªÙ Ø£ÙÙ‚Ù’Ø¯ÙØ§Ù…Ù Ø§Ù„Ù’Ø£ÙÙ…ÙÙ‘Ù‡ÙØ§ØªÙ', 'Cennet analarÄ±n ayaklarÄ± altÄ±ndadÄ±r.', 'NesÃ¢i'),
('hadis', 'ÙƒÙÙ„ÙÙ‘ Ù…ÙØ¹Ù’Ø±ÙÙˆÙÙ ØµÙØ¯ÙÙ‚ÙØ©ÙŒ', 'Her meÅŸru/gÃ¼zel iÅŸ bir sadakadÄ±r.', 'Buhari'),
('hadis', 'Ø§Ù„Ù’ÙƒÙÙ„ÙÙ…ÙØ©Ù Ø§Ù„Ø·ÙÙ‘ÙŠÙÙ‘Ø¨ÙØ©Ù ØµÙØ¯ÙÙ‚ÙØ©ÙŒ', 'GÃ¼zel sÃ¶z sadakadÄ±r.', 'Buhari'),
('hadis', 'Ø§Ù„Ù’Ù…ÙØ¤Ù’Ù…ÙÙ†Ù Ù…ÙØ±Ù’Ø¢Ø©Ù Ø§Ù„Ù’Ù…ÙØ¤Ù’Ù…ÙÙ†Ù', 'MÃ¼min, mÃ¼minin aynasÄ±dÄ±r.', 'Ebu Davud'),
('hadis', 'Ø§ØªÙÙ‘Ù‚Ù Ø§Ù„Ù„ÙÙ‘Ù‡Ù Ø­ÙÙŠÙ’Ø«ÙÙ…ÙØ§ ÙƒÙÙ†Ù’ØªÙ', 'Nerede olursan ol, Allah''tan kork.', 'Tirmizi'),
('hadis', 'Ø¥ÙÙŠÙÙ‘Ø§ÙƒÙÙ…Ù’ ÙˆÙØ§Ù„Ø¸ÙÙ‘Ù†ÙÙ‘ØŒ ÙÙØ¥ÙÙ†ÙÙ‘ Ø§Ù„Ø¸ÙÙ‘Ù†ÙÙ‘ Ø£ÙÙƒÙ’Ø°ÙØ¨Ù Ø§Ù„Ù’Ø­ÙØ¯ÙÙŠØ«Ù', 'Zandan sakÄ±nÄ±n, Ã§Ã¼nkÃ¼ zan sÃ¶zlerin en yalanÄ±dÄ±r.', 'Buhari'),
('hadis', 'Ø¥ÙÙ†ÙÙ‘ Ø§Ù„Ù„ÙÙ‘Ù‡Ù Ø¬ÙÙ…ÙÙŠÙ„ÙŒ ÙŠÙØ­ÙØ¨ÙÙ‘ Ø§Ù„Ù’Ø¬ÙÙ…ÙØ§Ù„Ù', 'ÅÃ¼phesiz Allah gÃ¼zeldir, gÃ¼zelliÄŸi sever.', 'MÃ¼slim'),
('hadis', 'Ø±ÙØ¶ÙØ§ Ø§Ù„Ø±ÙÙ‘Ø¨ÙÙ‘ ÙÙÙŠ Ø±ÙØ¶ÙØ§ Ø§Ù„Ù’ÙˆÙØ§Ù„ÙØ¯Ù', 'Rabbin rÄ±zasÄ± babanÄ±n (anne-babanÄ±n) rÄ±zasÄ±ndadÄ±r.', 'Tirmizi'),
('hadis', 'Ø£ÙØ­ÙØ¨ÙÙ‘ Ø§Ù„Ù’Ø¨ÙÙ„ÙØ§Ø¯Ù Ø¥ÙÙ„ÙÙ‰ Ø§Ù„Ù„ÙÙ‘Ù‡Ù Ù…ÙØ³ÙØ§Ø¬ÙØ¯ÙÙ‡ÙØ§', 'Åehirlerde Allah''a en sevimli olan yerler mescitlerdir.', 'MÃ¼slim'),
('hadis', 'Ù„ÙØ§ ÙŠÙØ¯Ù’Ø®ÙÙ„Ù Ø§Ù„Ù’Ø¬ÙÙ†ÙÙ‘Ø©Ù Ù…ÙÙ†Ù’ ÙƒÙØ§Ù†Ù ÙÙÙŠ Ù‚ÙÙ„Ù’Ø¨ÙÙ‡Ù Ù…ÙØ«Ù’Ù‚ÙØ§Ù„Ù Ø°ÙØ±ÙÙ‘Ø©Ù Ù…ÙÙ†Ù’ ÙƒÙØ¨Ù’Ø±Ù', 'Kalbinde zerre kadar kibir bulunan kimse cennete giremez.', 'MÃ¼slim'),
('hadis', 'Ø®ÙÙŠÙ’Ø±Ù Ø§Ù„Ù†ÙÙ‘Ø§Ø³Ù Ø£ÙÙ†Ù’ÙÙØ¹ÙÙ‡ÙÙ…Ù’ Ù„ÙÙ„Ù†ÙÙ‘Ø§Ø³Ù', 'Ä°nsanlarÄ±n en hayÄ±rlÄ±sÄ±, insanlara en faydalÄ± olanÄ±dÄ±r.', 'TaberÃ¢nÃ®'),
('hadis', 'Ø­ÙÙ‚ÙÙ‘ Ø§Ù„Ù’Ù…ÙØ³Ù’Ù„ÙÙ…Ù Ø¹ÙÙ„ÙÙ‰ Ø§Ù„Ù’Ù…ÙØ³Ù’Ù„ÙÙ…Ù Ø®ÙÙ…Ù’Ø³ÙŒ', 'MÃ¼slÃ¼manÄ±n MÃ¼slÃ¼man Ã¼zerindeki hakkÄ± beÅŸtir.', 'Buhari'),
('hadis', 'Ø§Ù„ØµÙÙ‘Ù„ÙØ§Ø©Ù Ù†ÙÙˆØ±ÙŒ', 'Namaz bir nurdur.', 'MÃ¼slim'),
('hadis', 'Ø§Ù„ØµÙÙ‘Ø¨Ù’Ø±Ù Ø¶ÙÙŠÙØ§Ø¡ÙŒ', 'SabÄ±r bir aydÄ±nlÄ±ktÄ±r.', 'MÃ¼slim'),
('hadis', 'Ø§Ù„Ù’ÙŠÙØ¯Ù Ø§Ù„Ù’Ø¹ÙÙ„Ù’ÙŠÙØ§ Ø®ÙÙŠÙ’Ø±ÙŒ Ù…ÙÙ†Ù Ø§Ù„Ù’ÙŠÙØ¯Ù Ø§Ù„Ø³ÙÙ‘ÙÙ’Ù„ÙÙ‰', 'Veren el, alan elden Ã¼stÃ¼ndÃ¼r.', 'Buhari'),
('hadis', 'Ø§Ù„Ù’Ø¹ÙÙŠÙ’Ù†Ù Ø­ÙÙ‚ÙŒÙ‘', 'Nazar (gÃ¶z deÄŸmesi) haktÄ±r.', 'Buhari'),
('hadis', 'Ø§Ù„Ø³ÙÙ‘ÙˆÙØ§ÙƒÙ Ù…ÙØ·Ù’Ù‡ÙØ±ÙØ©ÙŒ Ù„ÙÙ„Ù’ÙÙÙ…ÙØŒ Ù…ÙØ±Ù’Ø¶ÙØ§Ø©ÙŒ Ù„ÙÙ„Ø±ÙÙ‘Ø¨ÙÙ‘', 'Misvak kullanmak aÄŸzÄ± temizler, Rabbin rÄ±zasÄ±nÄ± kazandÄ±rÄ±r.', 'NesÃ¢i'),
('hadis', 'Ø£ÙÙÙ’Ø´ÙÙˆØ§ Ø§Ù„Ø³ÙÙ‘Ù„ÙØ§Ù…Ù Ø¨ÙÙŠÙ’Ù†ÙÙƒÙÙ…Ù’', 'AranÄ±zda selamÄ± yayÄ±n.', 'MÃ¼slim'),
('hadis', 'Ø§Ù„Ù’Ø¨ÙØ±ÙÙ‘ Ø­ÙØ³Ù’Ù†Ù Ø§Ù„Ù’Ø®ÙÙ„ÙÙ‚Ù', 'Ä°yilik, gÃ¼zel ahlaktan ibarettir.', 'MÃ¼slim'),
('hadis', 'Ù„ÙØ§ Ù‚ÙÙˆÙÙ‘Ø©Ù Ø¥ÙÙ„ÙÙ‘Ø§ Ø¨ÙØ§Ù„Ù„ÙÙ‘Ù‡Ù', 'GÃ¼Ã§ ve kuvvet ancak Allahâ€™tandÄ±r.', 'Ä°bn Mace'),
('hadis', 'Ø§Ø³Ù’ØªÙØ¹ÙÙŠÙ†ÙÙˆØ§ Ø¹ÙÙ„ÙÙ‰ Ù‚ÙØ¶ÙØ§Ø¡Ù Ø­ÙÙˆÙØ§Ø¦ÙØ¬ÙÙƒÙÙ…Ù’ Ø¨ÙØ§Ù„Ù’ÙƒÙØªÙ’Ù…ÙØ§Ù†Ù', 'Ä°htiyaÃ§larÄ±nÄ±zÄ± elde etmekte sessiz kalarak (sÄ±r saklayarak) yardÄ±m isteyin.', 'TaberÃ¢nÃ®'),
('hadis', 'ÙˆÙÙŠÙ’Ù„ÙŒ Ù„ÙÙ„Ù’Ø£ÙØ¹Ù’Ù‚ÙØ§Ø¨Ù Ù…ÙÙ†Ù Ø§Ù„Ù†ÙÙ‘Ø§Ø±Ù', 'Cehennem ateÅŸinden topuklarÄ±n (kuru yer bÄ±rakanlarÄ±n) vay haline.', 'Buhari'),
('hadis', 'Ø§Ù„Ø¸ÙÙ‘Ù„Ù’Ù…Ù Ø¸ÙÙ„ÙÙ…ÙØ§ØªÙŒ ÙŠÙÙˆÙ’Ù…Ù Ø§Ù„Ù’Ù‚ÙÙŠÙØ§Ù…ÙØ©Ù', 'ZulÃ¼m, kÄ±yamet gÃ¼nÃ¼nde zifiri karanlÄ±klar olacaktÄ±r.', 'Buhari'),
('hadis', 'Ø§Ù„Ù’Ø­ÙÙŠÙØ§Ø¡Ù Ø´ÙØ¹Ù’Ø¨ÙØ©ÙŒ Ù…ÙÙ†Ù Ø§Ù„Ù’Ø¥ÙÙŠÙ…ÙØ§Ù†Ù', 'Haya, imandan bir ÅŸubedir.', 'MÃ¼slim'),
('hadis', 'Ø¥ÙÙŠÙÙ‘Ø§ÙƒÙÙ…Ù’ ÙˆÙØ§Ù„Ù’Ø­ÙØ³ÙØ¯Ù', 'Hasetten (kÄ±skanÃ§lÄ±ktan) sakÄ±nÄ±n.', 'Ebu Davud'),
('hadis', 'Ø§ØªÙÙ‘Ù‚ÙÙˆØ§ Ø§Ù„Ù†ÙÙ‘Ø§Ø±Ù ÙˆÙÙ„ÙÙˆÙ’ Ø¨ÙØ´ÙÙ‚ÙÙ‘ ØªÙÙ…Ù’Ø±ÙØ©Ù', 'YarÄ±m hurma ile de olsa (sadaka vererek) kendinizi ateÅŸten koruyun.', 'Buhari'),
('hadis', 'Ø§Ù„Ø¯ÙÙ‘Ù†Ù’ÙŠÙØ§ Ø³ÙØ¬Ù’Ù†Ù Ø§Ù„Ù’Ù…ÙØ¤Ù’Ù…ÙÙ†ÙØŒ ÙˆÙØ¬ÙÙ†ÙÙ‘Ø©Ù Ø§Ù„Ù’ÙƒÙØ§ÙÙØ±Ù', 'DÃ¼nya mÃ¼minin zindanÄ±, kafirin cennetidir.', 'MÃ¼slim'),
('hadis', 'Ù…ÙØ§ Ù‚ÙÙ„ÙÙ‘ ÙˆÙÙƒÙÙÙÙ‰ØŒ Ø®ÙÙŠÙ’Ø±ÙŒ Ù…ÙÙ…ÙÙ‘Ø§ ÙƒÙØ«ÙØ±Ù ÙˆÙØ£ÙÙ„Ù’Ù‡ÙÙ‰', 'Az olup yeten ÅŸey, Ã§ok olup azdÄ±ran(Allah''tan oyalayan)dan hayÄ±rlÄ±dÄ±r.', 'Ahmed b. Hanbel'),
('hadis', 'Ø§Ù„Ù’Ù…ÙØ±Ù’Ø¡Ù Ù…ÙØ¹Ù Ù…ÙÙ†Ù’ Ø£ÙØ­ÙØ¨ÙÙ‘', 'KiÅŸi sevdiÄŸiyle beraberdir.', 'Buhari'),
('hadis', 'Ø·ÙÙ„ÙØ¨Ù Ø§Ù„Ù’Ø¹ÙÙ„Ù’Ù…Ù ÙÙØ±ÙÙŠØ¶ÙØ©ÙŒ Ø¹ÙÙ„ÙÙ‰ ÙƒÙÙ„ÙÙ‘ Ù…ÙØ³Ù’Ù„ÙÙ…Ù', 'Ä°lim taleb etmek, her MÃ¼slÃ¼mana farzdÄ±r.', 'Ä°bn Mace'),
('hadis', 'Ø¹ÙÙ„ÙÙ…ÙØ§Ø¡Ù Ø£ÙÙ…ÙÙ‘ØªÙÙŠ ÙƒÙØ£ÙÙ†Ù’Ø¨ÙÙŠÙØ§Ø¡Ù Ø¨ÙÙ†ÙÙŠ Ø¥ÙØ³Ù’Ø±ÙØ§Ø¦ÙÙŠÙ„Ù', 'Ãœmmetimin alimleri Ä°srailoÄŸullarÄ± peygamberleri gibidir. (Mecazen/ZayÄ±f Kaynak)', 'Acluni/KeÅŸful Hafa'),
('hadis', 'Ø¥ÙÙ†ÙÙ‘ Ø§Ù„Ù„ÙÙ‘Ù‡Ù Ù„ÙØ§ ÙŠÙÙ†Ù’Ø¸ÙØ±Ù Ø¥ÙÙ„ÙÙ‰ ØµÙÙˆÙØ±ÙÙƒÙÙ…Ù’ ÙˆÙØ£ÙÙ…Ù’ÙˆÙØ§Ù„ÙÙƒÙÙ…Ù’ØŒ ÙˆÙÙ„ÙÙƒÙÙ†Ù’ ÙŠÙÙ†Ù’Ø¸ÙØ±Ù Ø¥ÙÙ„ÙÙ‰ Ù‚ÙÙ„ÙÙˆØ¨ÙÙƒÙÙ…Ù’ ÙˆÙØ£ÙØ¹Ù’Ù…ÙØ§Ù„ÙÙƒÙÙ…Ù’', 'Allah sizin suretlerinize ve mallarÄ±nÄ±za bakmaz, kalplerinize ve amellerinize bakar.', 'MÃ¼slim'),
('hadis', 'Ø®ÙÙŠÙ’Ø±Ù Ø§Ù„Ù’Ø£ÙÙ…ÙÙˆØ±Ù Ø£ÙÙˆÙ’Ø³ÙØ·ÙÙ‡ÙØ§', 'Ä°ÅŸlerin en hayÄ±rlÄ±sÄ±, orta (dengeli) yollu olanÄ±dÄ±r.', 'BeyhÃ¢ki'),
('hadis', 'Ø¥ÙÙ†ÙÙ‘Ù…ÙØ§ Ø§Ù„ØµÙÙ‘Ø¨Ù’Ø±Ù Ø¹ÙÙ†Ù’Ø¯Ù Ø§Ù„ØµÙÙ‘Ø¯Ù’Ù…ÙØ©Ù Ø§Ù„Ù’Ø£ÙÙˆÙ„ÙÙ‰', 'GerÃ§ek sabÄ±r, musibetin ilk Ã§arptÄ±ÄŸÄ± andakidir.', 'Buhari'),
('hadis', 'Ù„ÙØ§ ØªÙÙ‚ÙÙˆÙ…Ù Ø§Ù„Ø³ÙÙ‘Ø§Ø¹ÙØ©Ù Ø­ÙØªÙÙ‘Ù‰ ÙŠÙÙ‚Ù’Ø¨ÙØ¶Ù Ø§Ù„Ù’Ø¹ÙÙ„Ù’Ù…Ù', 'Ä°lim yeryÃ¼zÃ¼nden alÄ±nmadÄ±kÃ§a kÄ±yamet kopmaz.', 'Buhari'),
('hadis', 'Ø§Ù„Ù’Ø¨ÙÙ„ÙØ§Ø¡Ù Ù…ÙÙˆÙÙƒÙÙ‘Ù„ÙŒ Ø¨ÙØ§Ù„Ù’Ù…ÙÙ†Ù’Ø·ÙÙ‚Ù', 'Bela sÃ¶z (dil) yÃ¼zÃ¼nden baÅŸa gelir. (Ä°nsanÄ±n baÅŸÄ±na ne gelirse dilinden gelir)', 'Taberani'),
('hadis', 'Ù…ÙÙ†Ù’ ØºÙØ´ÙÙ‘Ù†ÙØ§ ÙÙÙ„ÙÙŠÙ’Ø³Ù Ù…ÙÙ†ÙÙ‘Ø§', 'Bizi aldatan bizden deÄŸildir.', 'MÃ¼slim'),
('hadis', 'Ø§Ù„Ù’Ø¹ÙØ¬ÙÙ„ÙØ©Ù Ù…ÙÙ†Ù Ø§Ù„Ø´ÙÙ‘ÙŠÙ’Ø·ÙØ§Ù†ÙØŒ ÙˆÙØ§Ù„ØªÙÙ‘Ø£ÙÙ†ÙÙ‘ÙŠ Ù…ÙÙ†Ù Ø§Ù„Ù„ÙÙ‘Ù‡Ù', 'Acele ÅŸeytandandÄ±r, teenni (durup dÃ¼ÅŸÃ¼nme) Allah''tandÄ±r.', 'Tirmizi'),
('hadis', 'Ø®ÙÙŠÙ’Ø±Ù Ø¨ÙÙŠÙ’ØªÙ ÙÙÙŠ Ø§Ù„Ù’Ù…ÙØ³Ù’Ù„ÙÙ…ÙÙŠÙ†Ù Ø¨ÙÙŠÙ’ØªÙŒ ÙÙÙŠÙ‡Ù ÙŠÙØªÙÙŠÙ…ÙŒ ÙŠÙØ­Ù’Ø³ÙÙ†Ù Ø¥ÙÙ„ÙÙŠÙ’Ù‡Ù', 'MÃ¼slÃ¼manlar arasÄ±nda en hayÄ±rlÄ± ev, iÃ§inde yetime iyilik edilen evdir.', 'Ä°bn Mace');
