INSERT INTO public.tevekkul_vakti (content_text, source) VALUES
('Allah bize yeter, O ne güzel vekildir.', 'Âl-i İmrân Suresi, 173'),
('Şüphesiz her zorlukla beraber bir kolaylık vardır.', 'İnşirâh Suresi, 5'),
('Rabbin seni terk etmedi ve sana darılmadı.', 'Duhâ Suresi, 3'),
('Allah dilediğine hesapsız rızık verir.', 'Âl-i İmrân Suresi, 37'),
('Kalpler ancak Allah’ı anmakla mutmain olur.', 'Ra’d Suresi, 28'),
('Allah kuluna kâfi değil midir?', 'Zümer Suresi, 36'),
('Eğer Allah size yardım ederse, artık size galip gelecek kimse yoktur.', 'Âl-i İmrân Suresi, 160'),
('Gevşemeyin, hüzünlenmeyin. Eğer gerçekten inanıyorsanız, üstün olan sizsiniz.', 'Âl-i İmrân Suresi, 139'),
('O’nun emri, bir şeyi dilediği zaman ona sadece "Ol!" demektir; o da hemen oluverir.', 'Yâsin Suresi, 82'),
('Bana dua edin, size icabet edeyim.', 'Mü’min Suresi, 60'),
('Allah göklerin ve yerin nurudur.', 'Nûr Suresi, 35'),
('O, kullarının tevbesini kabul eden, kötülükleri bağışlayan ve yaptıklarınızı bilendir.', 'Şûrâ Suresi, 25'),
('Rabbim, benim göğsüme genişlik ver.', 'Tâhâ Suresi, 25'),
('Ben hüznümü ve kederimi ancak Allah’a şikayet ederim.', 'Yûsuf Suresi, 86'),
('Kullarım sana beni sorduklarında bilsinler ki ben çok yakınım.', 'Bakara Suresi, 186'),
('Kim sabreder ve bağışlarsa, şüphesiz bu, azmedilmeye değer işlerdendir.', 'Şûrâ Suresi, 43'),
('Kim Allah’a güvenirse, O ona yeter.', 'Talâk Suresi, 3'),
('Onların kalpleri Allah’ı anmakla huzur bulur.', 'Ra’d Suresi, 28'),
('Her şeyin mülkü O’nun elindedir.', 'Mü’minûn Suresi, 88'),
('Biz insana şah damarından daha yakınız.', 'Kâf Suresi, 16'),
('De ki: Sığınırım ben, o ağaran sabahın Rabbine.', 'Felâk Suresi, 1'),
('Rahman’ın kulları yeryüzünde vakarla yürürler.', 'Furkân Suresi, 63'),
('Şüphesiz Allah, sabredenlerle beraberdir.', 'Bakara Suresi, 153'),
('Nereye dönerseniz Allah’ın yüzü (ve rahmeti) oradadır.', 'Bakara Suresi, 115'),
('Rabbimiz! Bizi doğru yola ilettikten sonra kalplerimizi saptırma.', 'Âl-i İmrân Suresi, 8'),
('Allah, hiç kimseye gücünün yettiğinden fazlasını yüklemez.', 'Bakara Suresi, 286'),
('Her kim Allah’tan korkarsa, Allah ona bir çıkış yolu ihsan eder.', 'Talâk Suresi, 2'),
('İyilik ve takva (Allah’a karşı gelmekten sakınma) üzere yardımlaşın.', 'Mâide Suresi, 2'),
('O, her şeyi yaratmış ve ona bir ölçü, bir nizam vermiştir.', 'Furkân Suresi, 2'),
('Hamd, alemlerin Rabbi olan Allah’a mahsustur.', 'Fâtiha Suresi, 2'),
('O sana istediğini verdiğinde değil, sen O’ndan razı olduğunda huzur bulursun.', 'İslami Özlü Söz'),
('Sabır, boyun eğmek değil, mücadele etmektir.', 'Hz. Ömer (r.a.)'),
('Dua, inanan kimsenin silahıdır.', 'Hadis-i Şerif'),
('İstediğin kadar yaşa, mutlaka öleceksin. İstediğini sev, mutlaka ondan ayrılacaksın.', 'Hadis-i Şerif'),
('İnsanlara teşekkür etmeyen, Allah’a da şükretmez.', 'Hadis-i Şerif'),
('Ameller niyetlere göredir.', 'Hadis-i Şerif'),
('Sizin en hayırlınız, ahlakı en güzel olanınızdır.', 'Hadis-i Şerif'),
('Kolaylaştırın, zorlaştırmayın; müjdeleyin, nefret ettirmeyin.', 'Hadis-i Şerif'),
('Hayra vesile olan, o hayrı işlemiş gibidir.', 'Hadis-i Şerif'),
('Yarım hurma ile bile olsa, kendinizi ateşten koruyun.', 'Hadis-i Şerif'),
('Her kul öldüğü hal üzere diriltilir.', 'Hadis-i Şerif'),
('İki nimet vardır ki insanların çoğu onun kadrini bilmez: Sağlık ve boş vakit.', 'Hadis-i Şerif'),
('Sadaka malı eksiltmez.', 'Hadis-i Şerif'),
('Zulümden sakının! Çünkü zulüm, kıyamet gününde karanlıklar olacaktır.', 'Hadis-i Şerif'),
('Hiçbiriniz kendi nefsi için istediğini, din kardeşi için de istemedikçe kâmil mümin olamaz.', 'Hadis-i Şerif'),
('Cennet, annelerin ayakları altındadır.', 'Hadis-i Şerif'),
('Müminin durumu ne gariptir! Her hâli onun için bir hayırdır.', 'Hadis-i Şerif'),
('Güneşin doğduğu en hayırlı gün, Cuma günüdür.', 'Hadis-i Şerif'),
('Kim din kardeşinin bir ihtiyacını giderirse, Allah da onun ihtiyacını giderir.', 'Hadis-i Şerif'),
('Emanete hıyanet etme ki rızkın bereketlensin.', 'Hz. Ali (r.a.)'),
('Gecenin ne kadar karanlık olduğunu düşünme, sabahın ne kadar yakın olduğunu hatırla.', 'Mevlana Celaleddin Rumi'),
('Dua kapısını çalmasını bil, içeri buyur edileceksin.', 'Mevlana Celaleddin Rumi'),
('Yürek yanmadıkça, göz yaşarmaz.', 'Mevlana Celaleddin Rumi'),
('Bazen susmak, en büyük feryattır.', 'Hz. Ali (r.a.)'),
('Allah’ım! Beni, Senin rızan için sevdiğin kullarından eyle.', 'Günün Duası'),
('Gönlümüzü ferahlatacak olan ancak Sensin, Allah’ım.', 'Günün Duası'),
('Her şeyin anahtarı O’nun elindedir, O’ndan isteyin.', 'Günün Sözü'),
('Dert insana yol gösterir.', 'Mevlana Celaleddin Rumi'),
('En güçlü insan, öfkesine hakim olandır.', 'Hadis-i Şerif'),
('Eğer bir gün umudunu kaybedersen, gökyüzüne bak. Seni yaratan daima oradadır.', 'İslami Özlü Söz'),
('Gözyaşı, kalbin abdestidir.', 'Günün Sözü'),
('Niyetin ne ise nasibin de odur.', 'Yunus Emre'),
('Benlik davasını bırak, muhabbetten içeri gir.', 'Yunus Emre'),
('Kaderin ne ise ona rıza göster; çünkü isyan sadece acıyı artırır.', 'Hz. Ali (r.a.)'),
('Sadece Allah’a dayan, çünkü O’nun dışındaki her şey yıkılmaya mahkumdur.', 'Günün Sözü'),
('Rızkını dert etme; seni yaratan, seni unutmaz.', 'İslami Özlü Söz'),
('Affet ki, sen de affedilesin.', 'Günün Sözü'),
('En güzel rızık, huzurlu bir kalptir.', 'Günün Sözü'),
('Tevekkül, kalbin Allah’a tam bir teslimiyetle güvenmesidir.', 'Günün Sözü'),
('Gülümsemek sadakadır.', 'Hadis-i Şerif'),
('Sabrın da bir sonu, her karanlığın bir sabahı vardır.', 'Günün Sözü'),
('Allah’ın rahmetinden ümit kesmeyin.', 'Zümer Suresi, 53'),
('Kötülüğe iyilikle karşılık ver.', 'Mü’minûn Suresi, 96'),
('En hayırlı insan, insanlara en faydalı olandır.', 'Hadis-i Şerif'),
('Gönül kimi severse, güzel odur.', 'Mevlana Celaleddin Rumi'),
('Bir yetimin başını okşamak, kalbi yumuşatan en güzel sadakadır.', 'Hadis-i Şerif');
